export interface PermissionSeedItem {
  resource: string;
  action: string;
  permissionString: string;
  description: string;
  category: string;
}

export const SYSTEM_PERMISSIONS: PermissionSeedItem[] = [
  // Tenant & System (5)
  {
    resource: 'TENANT',
    action: 'CREATE',
    permissionString: 'tenant:create',
    description: 'Create new tenant subscribers',
    category: 'SYSTEM',
  },
  {
    resource: 'TENANT',
    action: 'READ',
    permissionString: 'tenant:read',
    description: 'View tenant details',
    category: 'SYSTEM',
  },
  {
    resource: 'TENANT',
    action: 'UPDATE',
    permissionString: 'tenant:update',
    description: 'Update tenant config',
    category: 'SYSTEM',
  },
  {
    resource: 'TENANT',
    action: 'DELETE',
    permissionString: 'tenant:delete',
    description: 'Deactivate tenant',
    category: 'SYSTEM',
  },
  {
    resource: 'AUDIT',
    action: 'READ',
    permissionString: 'audit:read',
    description: 'Read system audit trail',
    category: 'SYSTEM',
  },

  // School & Campus Configuration
  {
    resource: 'SCHOOL',
    action: 'CREATE',
    permissionString: 'school:create',
    description: 'Create schools',
    category: 'ACADEMIC',
  },
  {
    resource: 'SCHOOL',
    action: 'READ',
    permissionString: 'school:read',
    description: 'View schools',
    category: 'ACADEMIC',
  },
  {
    resource: 'SCHOOL',
    action: 'UPDATE',
    permissionString: 'school:update',
    description: 'Update school details',
    category: 'ACADEMIC',
  },
  {
    resource: 'CAMPUS',
    action: 'CREATE',
    permissionString: 'campus:create',
    description: 'Create new campus sites',
    category: 'ACADEMIC',
  },
  {
    resource: 'CAMPUS',
    action: 'READ',
    permissionString: 'campus:read',
    description: 'View campus sites',
    category: 'ACADEMIC',
  },
  {
    resource: 'CAMPUS',
    action: 'UPDATE',
    permissionString: 'campus:update',
    description: 'Update campus details',
    category: 'ACADEMIC',
  },
  {
    resource: 'CAMPUS',
    action: 'DELETE',
    permissionString: 'campus:delete',
    description: 'Archive or deactivate campus sites',
    category: 'ACADEMIC',
  },
  {
    resource: 'CAMPUS',
    action: 'MANAGE',
    permissionString: 'campus:manage',
    description: 'Manage campus sites',
    category: 'ACADEMIC',
  },
  {
    resource: 'ACADEMIC_YEAR',
    action: 'CREATE',
    permissionString: 'academic_year:create',
    description: 'Create academic years',
    category: 'ACADEMIC',
  },
  {
    resource: 'ACADEMIC_YEAR',
    action: 'READ',
    permissionString: 'academic_year:read',
    description: 'View academic calendars',
    category: 'ACADEMIC',
  },
  {
    resource: 'ACADEMIC_YEAR',
    action: 'UPDATE',
    permissionString: 'academic_year:update',
    description: 'Update academic calendar details',
    category: 'ACADEMIC',
  },
  {
    resource: 'ACADEMIC_YEAR',
    action: 'ACTIVATE',
    permissionString: 'academic_year:activate',
    description: 'Activate academic year and set as current session',
    category: 'ACADEMIC',
  },
  {
    resource: 'ACADEMIC_YEAR',
    action: 'CLOSE',
    permissionString: 'academic_year:close',
    description: 'Close academic year session',
    category: 'ACADEMIC',
  },
  {
    resource: 'ACADEMIC_YEAR',
    action: 'MANAGE',
    permissionString: 'academic_year:manage',
    description: 'Manage academic calendars',
    category: 'ACADEMIC',
  },
  {
    resource: 'SETTINGS',
    action: 'READ',
    permissionString: 'settings:read',
    description: 'View school operational settings',
    category: 'ACADEMIC',
  },
  {
    resource: 'SETTINGS',
    action: 'UPDATE',
    permissionString: 'settings:update',
    description: 'Update school operational settings',
    category: 'ACADEMIC',
  },
  {
    resource: 'BRANDING',
    action: 'READ',
    permissionString: 'branding:read',
    description: 'View school branding assets',
    category: 'ACADEMIC',
  },
  {
    resource: 'BRANDING',
    action: 'UPDATE',
    permissionString: 'branding:update',
    description: 'Update school branding assets and display themes',
    category: 'ACADEMIC',
  },
  {
    resource: 'RBAC',
    action: 'MANAGE',
    permissionString: 'rbac:manage',
    description: 'Manage roles and permissions',
    category: 'SYSTEM',
  },

  // Academic Structure & Curriculum
  {
    resource: 'CLASS',
    action: 'CREATE',
    permissionString: 'class:create',
    description: 'Create new grades/classes',
    category: 'ACADEMIC',
  },
  {
    resource: 'CLASS',
    action: 'READ',
    permissionString: 'class:read',
    description: 'View grades and classes',
    category: 'ACADEMIC',
  },
  {
    resource: 'CLASS',
    action: 'UPDATE',
    permissionString: 'class:update',
    description: 'Update grade/class details',
    category: 'ACADEMIC',
  },
  {
    resource: 'CLASS',
    action: 'DELETE',
    permissionString: 'class:delete',
    description: 'Archive or delete grades/classes',
    category: 'ACADEMIC',
  },
  {
    resource: 'CLASS',
    action: 'MANAGE',
    permissionString: 'class:manage',
    description: 'Full management of grades/classes',
    category: 'ACADEMIC',
  },
  {
    resource: 'SECTION',
    action: 'CREATE',
    permissionString: 'section:create',
    description: 'Create new class sections',
    category: 'ACADEMIC',
  },
  {
    resource: 'SECTION',
    action: 'READ',
    permissionString: 'section:read',
    description: 'View class sections',
    category: 'ACADEMIC',
  },
  {
    resource: 'SECTION',
    action: 'UPDATE',
    permissionString: 'section:update',
    description: 'Update section configurations',
    category: 'ACADEMIC',
  },
  {
    resource: 'SECTION',
    action: 'DELETE',
    permissionString: 'section:delete',
    description: 'Delete or archive sections',
    category: 'ACADEMIC',
  },
  {
    resource: 'SECTION',
    action: 'MANAGE',
    permissionString: 'section:manage',
    description: 'Full management of class sections',
    category: 'ACADEMIC',
  },
  {
    resource: 'ACADEMIC_CLASS',
    action: 'CREATE',
    permissionString: 'academic_class:create',
    description: 'Create academic class offerings',
    category: 'ACADEMIC',
  },
  {
    resource: 'ACADEMIC_CLASS',
    action: 'READ',
    permissionString: 'academic_class:read',
    description: 'View academic class offerings',
    category: 'ACADEMIC',
  },
  {
    resource: 'ACADEMIC_CLASS',
    action: 'UPDATE',
    permissionString: 'academic_class:update',
    description: 'Update academic class offerings',
    category: 'ACADEMIC',
  },
  {
    resource: 'ACADEMIC_CLASS',
    action: 'DELETE',
    permissionString: 'academic_class:delete',
    description: 'Archive or delete academic classes',
    category: 'ACADEMIC',
  },
  {
    resource: 'ACADEMIC_CLASS',
    action: 'MANAGE',
    permissionString: 'academic_class:manage',
    description: 'Full management of academic classes',
    category: 'ACADEMIC',
  },
  {
    resource: 'SUBJECT',
    action: 'CREATE',
    permissionString: 'subject:create',
    description: 'Create curriculum subjects',
    category: 'ACADEMIC',
  },
  {
    resource: 'SUBJECT',
    action: 'READ',
    permissionString: 'subject:read',
    description: 'View curriculum subjects',
    category: 'ACADEMIC',
  },
  {
    resource: 'SUBJECT',
    action: 'UPDATE',
    permissionString: 'subject:update',
    description: 'Update curriculum subjects',
    category: 'ACADEMIC',
  },
  {
    resource: 'SUBJECT',
    action: 'DELETE',
    permissionString: 'subject:delete',
    description: 'Archive or remove subjects',
    category: 'ACADEMIC',
  },
  {
    resource: 'SUBJECT',
    action: 'MANAGE',
    permissionString: 'subject:manage',
    description: 'Full management of curriculum subjects',
    category: 'ACADEMIC',
  },
  {
    resource: 'CLASS_SUBJECT',
    action: 'CREATE',
    permissionString: 'class_subject:create',
    description: 'Map subjects to classes',
    category: 'ACADEMIC',
  },
  {
    resource: 'CLASS_SUBJECT',
    action: 'READ',
    permissionString: 'class_subject:read',
    description: 'View class subject mappings',
    category: 'ACADEMIC',
  },
  {
    resource: 'CLASS_SUBJECT',
    action: 'UPDATE',
    permissionString: 'class_subject:update',
    description: 'Update class subject mappings',
    category: 'ACADEMIC',
  },
  {
    resource: 'CLASS_SUBJECT',
    action: 'DELETE',
    permissionString: 'class_subject:delete',
    description: 'Remove class subject mappings',
    category: 'ACADEMIC',
  },
  {
    resource: 'CLASS_SUBJECT',
    action: 'MANAGE',
    permissionString: 'class_subject:manage',
    description: 'Full management of class subject mappings',
    category: 'ACADEMIC',
  },
  {
    resource: 'TEACHER_ASSIGNMENT',
    action: 'CREATE',
    permissionString: 'teacher_assignment:create',
    description: 'Assign teachers to subjects/sections',
    category: 'ACADEMIC',
  },
  {
    resource: 'TEACHER_ASSIGNMENT',
    action: 'READ',
    permissionString: 'teacher_assignment:read',
    description: 'View teacher subject assignments',
    category: 'ACADEMIC',
  },
  {
    resource: 'TEACHER_ASSIGNMENT',
    action: 'UPDATE',
    permissionString: 'teacher_assignment:update',
    description: 'Update teacher subject assignments',
    category: 'ACADEMIC',
  },
  {
    resource: 'TEACHER_ASSIGNMENT',
    action: 'DELETE',
    permissionString: 'teacher_assignment:delete',
    description: 'Remove teacher subject assignments',
    category: 'ACADEMIC',
  },
  {
    resource: 'TEACHER_ASSIGNMENT',
    action: 'MANAGE',
    permissionString: 'teacher_assignment:manage',
    description: 'Full management of teacher subject assignments',
    category: 'ACADEMIC',
  },
  {
    resource: 'ACADEMIC_ENROLLMENT',
    action: 'CREATE',
    permissionString: 'academic_enrollment:create',
    description: 'Enroll students into academic classes',
    category: 'ACADEMIC',
  },
  {
    resource: 'ACADEMIC_ENROLLMENT',
    action: 'READ',
    permissionString: 'academic_enrollment:read',
    description: 'View academic class enrollments',
    category: 'ACADEMIC',
  },
  {
    resource: 'ACADEMIC_ENROLLMENT',
    action: 'UPDATE',
    permissionString: 'academic_enrollment:update',
    description: 'Update enrollment and roll numbers',
    category: 'ACADEMIC',
  },
  {
    resource: 'ACADEMIC_ENROLLMENT',
    action: 'DELETE',
    permissionString: 'academic_enrollment:delete',
    description: 'Remove student academic enrollments',
    category: 'ACADEMIC',
  },
  {
    resource: 'ACADEMIC_ENROLLMENT',
    action: 'MANAGE',
    permissionString: 'academic_enrollment:manage',
    description: 'Full management of academic enrollments',
    category: 'ACADEMIC',
  },
  {
    resource: 'CLASS_TEACHER',
    action: 'ASSIGN',
    permissionString: 'class_teacher:assign',
    description: 'Assign class teachers to sections/academic classes',
    category: 'ACADEMIC',
  },
  {
    resource: 'TIMETABLE',
    action: 'CREATE',
    permissionString: 'timetable:create',
    description: 'Generate schedule timetable',
    category: 'ACADEMIC',
  },
  {
    resource: 'TIMETABLE',
    action: 'READ',
    permissionString: 'timetable:read',
    description: 'View schedule timetable',
    category: 'ACADEMIC',
  },
  {
    resource: 'TIMETABLE',
    action: 'UPDATE',
    permissionString: 'timetable:update',
    description: 'Modify schedule timetable',
    category: 'ACADEMIC',
  },
  {
    resource: 'TIMETABLE',
    action: 'PUBLISH',
    permissionString: 'timetable:publish',
    description: 'Publish timetable to students/teachers',
    category: 'ACADEMIC',
  },
  {
    resource: 'TIMETABLE',
    action: 'ARCHIVE',
    permissionString: 'timetable:archive',
    description: 'Archive active or historical timetable versions',
    category: 'ACADEMIC',
  },
  {
    resource: 'TIMETABLE',
    action: 'DELETE',
    permissionString: 'timetable:delete',
    description: 'Delete draft timetable versions',
    category: 'ACADEMIC',
  },
  {
    resource: 'TIMETABLE',
    action: 'MANAGE',
    permissionString: 'timetable:manage',
    description: 'Full management of timetables and scheduling',
    category: 'ACADEMIC',
  },
  {
    resource: 'TIMETABLE_ENTRY',
    action: 'CREATE',
    permissionString: 'timetable_entry:create',
    description: 'Schedule class slot entries',
    category: 'ACADEMIC',
  },
  {
    resource: 'TIMETABLE_ENTRY',
    action: 'READ',
    permissionString: 'timetable_entry:read',
    description: 'View scheduled timetable entries',
    category: 'ACADEMIC',
  },
  {
    resource: 'TIMETABLE_ENTRY',
    action: 'UPDATE',
    permissionString: 'timetable_entry:update',
    description: 'Modify scheduled timetable entries',
    category: 'ACADEMIC',
  },
  {
    resource: 'TIMETABLE_ENTRY',
    action: 'DELETE',
    permissionString: 'timetable_entry:delete',
    description: 'Remove scheduled timetable entries',
    category: 'ACADEMIC',
  },
  {
    resource: 'PERIOD',
    action: 'CREATE',
    permissionString: 'period:create',
    description: 'Create period and bell schedule configurations',
    category: 'ACADEMIC',
  },
  {
    resource: 'PERIOD',
    action: 'READ',
    permissionString: 'period:read',
    description: 'View periods and bell schedule configurations',
    category: 'ACADEMIC',
  },
  {
    resource: 'PERIOD',
    action: 'UPDATE',
    permissionString: 'period:update',
    description: 'Update periods and bell schedule configurations',
    category: 'ACADEMIC',
  },
  {
    resource: 'PERIOD',
    action: 'DELETE',
    permissionString: 'period:delete',
    description: 'Archive or remove periods',
    category: 'ACADEMIC',
  },
  {
    resource: 'PERIOD',
    action: 'MANAGE',
    permissionString: 'period:manage',
    description: 'Full management of period configurations',
    category: 'ACADEMIC',
  },
  {
    resource: 'ROOM',
    action: 'CREATE',
    permissionString: 'room:create',
    description: 'Create classrooms and physical facilities',
    category: 'ACADEMIC',
  },
  {
    resource: 'ROOM',
    action: 'READ',
    permissionString: 'room:read',
    description: 'View classrooms and room capacities',
    category: 'ACADEMIC',
  },
  {
    resource: 'ROOM',
    action: 'UPDATE',
    permissionString: 'room:update',
    description: 'Update classroom details and capacities',
    category: 'ACADEMIC',
  },
  {
    resource: 'ROOM',
    action: 'DELETE',
    permissionString: 'room:delete',
    description: 'Archive or remove classrooms',
    category: 'ACADEMIC',
  },
  {
    resource: 'ROOM',
    action: 'MANAGE',
    permissionString: 'room:manage',
    description: 'Full management of classrooms and facilities',
    category: 'ACADEMIC',
  },

  // Student & Admissions (11)
  {
    resource: 'STUDENT',
    action: 'CREATE',
    permissionString: 'student:create',
    description: 'Register new student profile',
    category: 'STUDENT',
  },
  {
    resource: 'STUDENT',
    action: 'READ',
    permissionString: 'student:read',
    description: 'View student profile and records',
    category: 'STUDENT',
  },
  {
    resource: 'STUDENT',
    action: 'UPDATE',
    permissionString: 'student:update',
    description: 'Modify student profile',
    category: 'STUDENT',
  },
  {
    resource: 'STUDENT',
    action: 'DELETE',
    permissionString: 'student:delete',
    description: 'Archive or soft delete student profile',
    category: 'STUDENT',
  },
  {
    resource: 'STUDENT',
    action: 'PROMOTE',
    permissionString: 'student:promote',
    description: 'Promote student to next academic grade',
    category: 'STUDENT',
  },
  {
    resource: 'STUDENT',
    action: 'TRANSFER',
    permissionString: 'student:transfer',
    description: 'Transfer or issue TC to student',
    category: 'STUDENT',
  },
  {
    resource: 'STUDENT',
    action: 'ADMIT',
    permissionString: 'student:admit',
    description: 'Admit student into the institution',
    category: 'STUDENT',
  },
  {
    resource: 'STUDENT',
    action: 'ACTIVATE',
    permissionString: 'student:activate',
    description: 'Activate student status',
    category: 'STUDENT',
  },
  {
    resource: 'STUDENT',
    action: 'SUSPEND',
    permissionString: 'student:suspend',
    description: 'Suspend student record',
    category: 'STUDENT',
  },
  {
    resource: 'STUDENT',
    action: 'WITHDRAW',
    permissionString: 'student:withdraw',
    description: 'Process student withdrawal',
    category: 'STUDENT',
  },
  {
    resource: 'STUDENT',
    action: 'GRADUATE',
    permissionString: 'student:graduate',
    description: 'Graduate student record',
    category: 'STUDENT',
  },
  {
    resource: 'STUDENT',
    action: 'ARCHIVE',
    permissionString: 'student:archive',
    description: 'Archive student historical record',
    category: 'STUDENT',
  },

  // Guardian Management (4)
  {
    resource: 'GUARDIAN',
    action: 'CREATE',
    permissionString: 'guardian:create',
    description: 'Create parent/guardian record',
    category: 'STUDENT',
  },
  {
    resource: 'GUARDIAN',
    action: 'READ',
    permissionString: 'guardian:read',
    description: 'View parent/guardian record',
    category: 'STUDENT',
  },
  {
    resource: 'GUARDIAN',
    action: 'UPDATE',
    permissionString: 'guardian:update',
    description: 'Update parent/guardian record',
    category: 'STUDENT',
  },
  {
    resource: 'GUARDIAN',
    action: 'DELETE',
    permissionString: 'guardian:delete',
    description: 'Remove or archive parent/guardian record',
    category: 'STUDENT',
  },

  // Student-Guardian Relationships (4)
  {
    resource: 'RELATIONSHIP',
    action: 'CREATE',
    permissionString: 'relationship:create',
    description: 'Link guardian to student',
    category: 'STUDENT',
  },
  {
    resource: 'RELATIONSHIP',
    action: 'READ',
    permissionString: 'relationship:read',
    description: 'View student-guardian relationships',
    category: 'STUDENT',
  },
  {
    resource: 'RELATIONSHIP',
    action: 'UPDATE',
    permissionString: 'relationship:update',
    description: 'Update student-guardian relationship flags and permissions',
    category: 'STUDENT',
  },
  {
    resource: 'RELATIONSHIP',
    action: 'DELETE',
    permissionString: 'relationship:delete',
    description: 'Unlink guardian from student',
    category: 'STUDENT',
  },

  // Student Enrollment (4)
  {
    resource: 'ENROLLMENT',
    action: 'CREATE',
    permissionString: 'enrollment:create',
    description: 'Enroll student into academic session',
    category: 'ACADEMIC',
  },
  {
    resource: 'ENROLLMENT',
    action: 'READ',
    permissionString: 'enrollment:read',
    description: 'View student enrollment history',
    category: 'ACADEMIC',
  },
  {
    resource: 'ENROLLMENT',
    action: 'UPDATE',
    permissionString: 'enrollment:update',
    description: 'Update enrollment record details',
    category: 'ACADEMIC',
  },
  {
    resource: 'ENROLLMENT',
    action: 'TRANSFER',
    permissionString: 'enrollment:transfer',
    description: 'Transfer enrollment between campuses or sessions',
    category: 'ACADEMIC',
  },

  // Student Documents (5)
  {
    resource: 'STUDENT_DOCUMENT',
    action: 'CREATE',
    permissionString: 'student_document:create',
    description: 'Upload student compliance and identity documents',
    category: 'STUDENT',
  },
  {
    resource: 'STUDENT_DOCUMENT',
    action: 'READ',
    permissionString: 'student_document:read',
    description: 'View student documents',
    category: 'STUDENT',
  },
  {
    resource: 'STUDENT_DOCUMENT',
    action: 'UPDATE',
    permissionString: 'student_document:update',
    description: 'Update student document metadata',
    category: 'STUDENT',
  },
  {
    resource: 'STUDENT_DOCUMENT',
    action: 'VERIFY',
    permissionString: 'student_document:verify',
    description: 'Verify or reject student documents',
    category: 'STUDENT',
  },
  {
    resource: 'STUDENT_DOCUMENT',
    action: 'DELETE',
    permissionString: 'student_document:delete',
    description: 'Delete student document',
    category: 'STUDENT',
  },
  {
    resource: 'ADMISSION',
    action: 'CREATE',
    permissionString: 'admission:create',
    description: 'Submit admission application',
    category: 'ADMISSION',
  },
  {
    resource: 'ADMISSION',
    action: 'READ',
    permissionString: 'admission:read',
    description: 'View admission applications',
    category: 'ADMISSION',
  },
  {
    resource: 'ADMISSION',
    action: 'REVIEW',
    permissionString: 'admission:review',
    description: 'Review and verify applicant documents',
    category: 'ADMISSION',
  },
  {
    resource: 'ADMISSION',
    action: 'APPROVE',
    permissionString: 'admission:approve',
    description: 'Grant official admission approval',
    category: 'ADMISSION',
  },
  {
    resource: 'ADMISSION',
    action: 'REJECT',
    permissionString: 'admission:reject',
    description: 'Reject admission application',
    category: 'ADMISSION',
  },

  // Attendance & Classroom
  {
    resource: 'ATTENDANCE',
    action: 'CREATE',
    permissionString: 'attendance:create',
    description: 'Create or draft student attendance',
    category: 'ATTENDANCE',
  },
  {
    resource: 'ATTENDANCE',
    action: 'MARK',
    permissionString: 'attendance:mark',
    description: 'Submit daily attendance for students',
    category: 'ATTENDANCE',
  },
  {
    resource: 'ATTENDANCE',
    action: 'READ',
    permissionString: 'attendance:read',
    description: 'View student attendance records',
    category: 'ATTENDANCE',
  },
  {
    resource: 'ATTENDANCE',
    action: 'UPDATE',
    permissionString: 'attendance:update',
    description: 'Correct previously submitted attendance',
    category: 'ATTENDANCE',
  },
  {
    resource: 'ATTENDANCE',
    action: 'SUBMIT',
    permissionString: 'attendance:submit',
    description: 'Submit class attendance for review/finalization',
    category: 'ATTENDANCE',
  },
  {
    resource: 'ATTENDANCE',
    action: 'APPROVE',
    permissionString: 'attendance:approve',
    description: 'Approve submitted class attendance',
    category: 'ATTENDANCE',
  },
  {
    resource: 'ATTENDANCE',
    action: 'LOCK',
    permissionString: 'attendance:lock',
    description: 'Lock attendance registers against editing',
    category: 'ATTENDANCE',
  },
  {
    resource: 'ATTENDANCE',
    action: 'CORRECT',
    permissionString: 'attendance:correct',
    description: 'Request or execute attendance corrections',
    category: 'ATTENDANCE',
  },
  {
    resource: 'ATTENDANCE',
    action: 'REPORT',
    permissionString: 'attendance:report',
    description: 'View attendance analytics and summaries',
    category: 'ATTENDANCE',
  },
  {
    resource: 'ATTENDANCE',
    action: 'EXPORT',
    permissionString: 'attendance:export',
    description: 'Download attendance reports',
    category: 'ATTENDANCE',
  },
  {
    resource: 'HOLIDAY',
    action: 'CREATE',
    permissionString: 'holiday:create',
    description: 'Declare school holidays and calendar breaks',
    category: 'ATTENDANCE',
  },
  {
    resource: 'HOLIDAY',
    action: 'READ',
    permissionString: 'holiday:read',
    description: 'View declared school holidays',
    category: 'ATTENDANCE',
  },
  {
    resource: 'HOLIDAY',
    action: 'UPDATE',
    permissionString: 'holiday:update',
    description: 'Modify declared school holidays',
    category: 'ATTENDANCE',
  },
  {
    resource: 'HOLIDAY',
    action: 'DELETE',
    permissionString: 'holiday:delete',
    description: 'Remove declared school holidays',
    category: 'ATTENDANCE',
  },
  {
    resource: 'STAFF_ATTENDANCE',
    action: 'MARK',
    permissionString: 'staff_attendance:mark',
    description: 'Record employee attendance',
    category: 'HR',
  },
  {
    resource: 'STAFF_ATTENDANCE',
    action: 'READ',
    permissionString: 'staff_attendance:read',
    description: 'View employee attendance logs',
    category: 'HR',
  },

  // Homework & Assignments (18)
  {
    resource: 'HOMEWORK',
    action: 'CREATE',
    permissionString: 'homework:create',
    description: 'Publish homework assignments',
    category: 'ACADEMIC',
  },
  {
    resource: 'HOMEWORK',
    action: 'READ',
    permissionString: 'homework:read',
    description: 'View assigned homework',
    category: 'ACADEMIC',
  },
  {
    resource: 'HOMEWORK',
    action: 'UPDATE',
    permissionString: 'homework:update',
    description: 'Edit homework details and due date',
    category: 'ACADEMIC',
  },
  {
    resource: 'HOMEWORK',
    action: 'GRADE',
    permissionString: 'homework:grade',
    description: 'Grade and provide feedback on submissions',
    category: 'ACADEMIC',
  },
  {
    resource: 'HOMEWORK',
    action: 'SUBMIT',
    permissionString: 'homework:submit',
    description: 'Upload completed homework solution',
    category: 'ACADEMIC',
  },
  {
    resource: 'ASSIGNMENT',
    action: 'CREATE',
    permissionString: 'assignment:create',
    description: 'Create assignment drafts',
    category: 'ACADEMIC',
  },
  {
    resource: 'ASSIGNMENT',
    action: 'READ',
    permissionString: 'assignment:read',
    description: 'View assignments and deadlines',
    category: 'ACADEMIC',
  },
  {
    resource: 'ASSIGNMENT',
    action: 'UPDATE',
    permissionString: 'assignment:update',
    description: 'Edit assignment details and due dates',
    category: 'ACADEMIC',
  },
  {
    resource: 'ASSIGNMENT',
    action: 'DELETE',
    permissionString: 'assignment:delete',
    description: 'Delete assignment drafts',
    category: 'ACADEMIC',
  },
  {
    resource: 'ASSIGNMENT',
    action: 'PUBLISH',
    permissionString: 'assignment:publish',
    description: 'Publish assignments to enrolled students',
    category: 'ACADEMIC',
  },
  {
    resource: 'ASSIGNMENT',
    action: 'CLOSE',
    permissionString: 'assignment:close',
    description: 'Close assignments to prevent further submissions',
    category: 'ACADEMIC',
  },
  {
    resource: 'ASSIGNMENT',
    action: 'ARCHIVE',
    permissionString: 'assignment:archive',
    description: 'Archive historical assignments',
    category: 'ACADEMIC',
  },
  {
    resource: 'SUBMISSION',
    action: 'CREATE',
    permissionString: 'submission:create',
    description: 'Submit assignment solutions',
    category: 'ACADEMIC',
  },
  {
    resource: 'SUBMISSION',
    action: 'READ',
    permissionString: 'submission:read',
    description: 'View student submissions, text, and attachments',
    category: 'ACADEMIC',
  },
  {
    resource: 'SUBMISSION',
    action: 'UPDATE',
    permissionString: 'submission:update',
    description: 'Save draft submissions or update solutions',
    category: 'ACADEMIC',
  },
  {
    resource: 'SUBMISSION',
    action: 'GRADE',
    permissionString: 'submission:grade',
    description: 'Evaluate submissions, assign score, and provide feedback',
    category: 'ACADEMIC',
  },
  {
    resource: 'SUBMISSION',
    action: 'RETURN',
    permissionString: 'submission:return',
    description: 'Return submissions for student revisions',
    category: 'ACADEMIC',
  },
  {
    resource: 'ASSIGNMENT',
    action: 'REPORT',
    permissionString: 'assignment_report:read',
    description: 'View assignment analytics and submission metrics',
    category: 'ACADEMIC',
  },

  // Examinations & Grading (24)
  {
    resource: 'EXAM',
    action: 'CREATE',
    permissionString: 'exam:create',
    description: 'Configure examination cycles',
    category: 'EXAMINATION',
  },
  {
    resource: 'EXAM',
    action: 'READ',
    permissionString: 'exam:read',
    description: 'View exam details',
    category: 'EXAMINATION',
  },
  {
    resource: 'EXAM',
    action: 'UPDATE',
    permissionString: 'exam:update',
    description: 'Edit exam configuration and dates',
    category: 'EXAMINATION',
  },
  {
    resource: 'EXAM',
    action: 'DELETE',
    permissionString: 'exam:delete',
    description: 'Delete draft exams',
    category: 'EXAMINATION',
  },
  {
    resource: 'EXAM',
    action: 'SCHEDULE',
    permissionString: 'exam:schedule',
    description: 'Schedule exam timetable and rooms',
    category: 'EXAMINATION',
  },
  {
    resource: 'EXAM',
    action: 'PUBLISH',
    permissionString: 'exam:publish',
    description: 'Publish examination timetables',
    category: 'EXAMINATION',
  },
  {
    resource: 'EXAM',
    action: 'LOCK',
    permissionString: 'exam:lock',
    description: 'Lock completed examination entries',
    category: 'EXAMINATION',
  },
  {
    resource: 'EXAM',
    action: 'ARCHIVE',
    permissionString: 'exam:archive',
    description: 'Archive completed exams',
    category: 'EXAMINATION',
  },
  {
    resource: 'MARKS',
    action: 'READ',
    permissionString: 'marks:read',
    description: 'View student marks sheets',
    category: 'EXAMINATION',
  },
  {
    resource: 'MARKS',
    action: 'ENTRY',
    permissionString: 'marks:entry',
    description: 'Input student marks for subject',
    category: 'EXAMINATION',
  },
  {
    resource: 'MARKS',
    action: 'UPDATE',
    permissionString: 'marks:update',
    description: 'Update draft marks entries',
    category: 'EXAMINATION',
  },
  {
    resource: 'MARKS',
    action: 'VERIFY',
    permissionString: 'marks:verify',
    description: 'Verify and approve grade sheets',
    category: 'EXAMINATION',
  },
  {
    resource: 'MARKS',
    action: 'CORRECT',
    permissionString: 'marks:correct',
    description: 'Request or execute marks corrections',
    category: 'EXAMINATION',
  },
  {
    resource: 'MARKS',
    action: 'LOCK',
    permissionString: 'marks:lock',
    description: 'Lock marks to prevent further editing',
    category: 'EXAMINATION',
  },
  {
    resource: 'RESULT',
    action: 'CALCULATE',
    permissionString: 'result:calculate',
    description: 'Calculate student results, percentages, and grades',
    category: 'EXAMINATION',
  },
  {
    resource: 'RESULT',
    action: 'READ',
    permissionString: 'result:read',
    description: 'View student examination results',
    category: 'EXAMINATION',
  },
  {
    resource: 'RESULT',
    action: 'APPROVE',
    permissionString: 'result:approve',
    description: 'Approve calculated examination results',
    category: 'EXAMINATION',
  },
  {
    resource: 'RESULT',
    action: 'PUBLISH',
    permissionString: 'result:publish',
    description: 'Publish results to students and parents',
    category: 'EXAMINATION',
  },
  {
    resource: 'RESULT',
    action: 'CORRECT',
    permissionString: 'result:correct',
    description: 'Modify or revise published results',
    category: 'EXAMINATION',
  },
  {
    resource: 'REPORT_CARD',
    action: 'READ',
    permissionString: 'report_card:read',
    description: 'View report card summaries',
    category: 'EXAMINATION',
  },
  {
    resource: 'REPORT_CARD',
    action: 'GENERATE',
    permissionString: 'report_card:generate',
    description: 'Compile grade report cards',
    category: 'EXAMINATION',
  },
  {
    resource: 'REPORT_CARD',
    action: 'PUBLISH',
    permissionString: 'report_card:publish',
    description: 'Release report cards to students/parents',
    category: 'EXAMINATION',
  },
  {
    resource: 'GRADING_SCHEME',
    action: 'READ',
    permissionString: 'grading_scheme:read',
    description: 'View grading scales and schemes',
    category: 'EXAMINATION',
  },
  {
    resource: 'GRADING_SCHEME',
    action: 'MANAGE',
    permissionString: 'grading_scheme:manage',
    description: 'Create and edit grading schemes',
    category: 'EXAMINATION',
  },

  // Fees & Financial Ledger
  {
    resource: 'FEE_CATEGORY',
    action: 'CREATE',
    permissionString: 'fee_category:create',
    description: 'Define fee categories and heads',
    category: 'FINANCE',
  },
  {
    resource: 'FEE_CATEGORY',
    action: 'READ',
    permissionString: 'fee_category:read',
    description: 'View fee categories and heads',
    category: 'FINANCE',
  },
  {
    resource: 'FEE_CATEGORY',
    action: 'UPDATE',
    permissionString: 'fee_category:update',
    description: 'Update fee categories',
    category: 'FINANCE',
  },
  {
    resource: 'FEE_CATEGORY',
    action: 'DELETE',
    permissionString: 'fee_category:delete',
    description: 'Delete fee categories',
    category: 'FINANCE',
  },
  {
    resource: 'FEE_STRUCTURE',
    action: 'CREATE',
    permissionString: 'fee_structure:create',
    description: 'Define class fee blueprints',
    category: 'FINANCE',
  },
  {
    resource: 'FEE_STRUCTURE',
    action: 'READ',
    permissionString: 'fee_structure:read',
    description: 'View fee structures and heads',
    category: 'FINANCE',
  },
  {
    resource: 'FEE_STRUCTURE',
    action: 'UPDATE',
    permissionString: 'fee_structure:update',
    description: 'Adjust fee structure rules',
    category: 'FINANCE',
  },
  {
    resource: 'FEE_STRUCTURE',
    action: 'DELETE',
    permissionString: 'fee_structure:delete',
    description: 'Delete fee structure',
    category: 'FINANCE',
  },
  {
    resource: 'FEE_ASSIGNMENT',
    action: 'CREATE',
    permissionString: 'fee_assignment:create',
    description: 'Assign fee structures to students',
    category: 'FINANCE',
  },
  {
    resource: 'FEE_ASSIGNMENT',
    action: 'READ',
    permissionString: 'fee_assignment:read',
    description: 'View student fee assignments and concessions',
    category: 'FINANCE',
  },
  {
    resource: 'FEE_ASSIGNMENT',
    action: 'UPDATE',
    permissionString: 'fee_assignment:update',
    description: 'Update student fee assignments and concessions',
    category: 'FINANCE',
  },
  {
    resource: 'FEE_ASSIGNMENT',
    action: 'DELETE',
    permissionString: 'fee_assignment:delete',
    description: 'Delete student fee assignments',
    category: 'FINANCE',
  },
  {
    resource: 'FEE_INVOICE',
    action: 'CREATE',
    permissionString: 'fee_invoice:create',
    description: 'Generate fee invoices for students',
    category: 'FINANCE',
  },
  {
    resource: 'FEE_INVOICE',
    action: 'READ',
    permissionString: 'fee_invoice:read',
    description: 'View fee invoices and balances',
    category: 'FINANCE',
  },
  {
    resource: 'FEE_INVOICE',
    action: 'VOID',
    permissionString: 'fee_invoice:void',
    description: 'Cancel erroneous fee invoices',
    category: 'FINANCE',
  },
  {
    resource: 'PAYMENT',
    action: 'COLLECT',
    permissionString: 'payment:collect',
    description: 'Collect and record fee payments',
    category: 'FINANCE',
  },
  {
    resource: 'PAYMENT',
    action: 'READ',
    permissionString: 'payment:read',
    description: 'View receipt ledgers',
    category: 'FINANCE',
  },
  {
    resource: 'PAYMENT',
    action: 'REFUND',
    permissionString: 'payment:refund',
    description: 'Process fee refunds',
    category: 'FINANCE',
  },
  {
    resource: 'PAYMENT',
    action: 'RECONCILE',
    permissionString: 'payment:reconcile',
    description: 'Reconcile gateway payments and transactions',
    category: 'FINANCE',
  },
  {
    resource: 'FINANCE_REPORT',
    action: 'READ',
    permissionString: 'finance_report:read',
    description: 'View financial summaries and defaulters reports',
    category: 'FINANCE',
  },
  {
    resource: 'INCOME_EXPENSE',
    action: 'MANAGE',
    permissionString: 'income_expense:manage',
    description: 'Record and manage income and expense ledgers',
    category: 'FINANCE',
  },

  // HR & Payroll
  {
    resource: 'TEACHER',
    action: 'MANAGE',
    permissionString: 'teacher:manage',
    description: 'Manage teaching faculty profiles',
    category: 'HR',
  },
  {
    resource: 'STAFF',
    action: 'MANAGE',
    permissionString: 'staff:manage',
    description: 'Manage non-teaching staff profiles',
    category: 'HR',
  },
  {
    resource: 'EMPLOYEE',
    action: 'CREATE',
    permissionString: 'employee:create',
    description: 'Create new employee profile',
    category: 'HR',
  },
  {
    resource: 'EMPLOYEE',
    action: 'READ',
    permissionString: 'employee:read',
    description: 'View employee records',
    category: 'HR',
  },
  {
    resource: 'EMPLOYEE',
    action: 'UPDATE',
    permissionString: 'employee:update',
    description: 'Update employee profile details',
    category: 'HR',
  },
  {
    resource: 'EMPLOYEE',
    action: 'DELETE',
    permissionString: 'employee:delete',
    description: 'Archive or soft delete employee',
    category: 'HR',
  },
  {
    resource: 'EMPLOYEE',
    action: 'ACTIVATE',
    permissionString: 'employee:activate',
    description: 'Activate employee account',
    category: 'HR',
  },
  {
    resource: 'EMPLOYEE',
    action: 'DEACTIVATE',
    permissionString: 'employee:deactivate',
    description: 'Deactivate employee account',
    category: 'HR',
  },
  {
    resource: 'EMPLOYEE',
    action: 'SUSPEND',
    permissionString: 'employee:suspend',
    description: 'Suspend employee account',
    category: 'HR',
  },
  {
    resource: 'EMPLOYEE',
    action: 'TERMINATE',
    permissionString: 'employee:terminate',
    description: 'Terminate employee contract',
    category: 'HR',
  },
  {
    resource: 'EMPLOYEE',
    action: 'RESTORE',
    permissionString: 'employee:restore',
    description: 'Restore terminated or inactive employee',
    category: 'HR',
  },
  {
    resource: 'TEACHER',
    action: 'CREATE',
    permissionString: 'teacher:create',
    description: 'Create teacher academic profile',
    category: 'HR',
  },
  {
    resource: 'TEACHER',
    action: 'READ',
    permissionString: 'teacher:read',
    description: 'View teacher academic profiles',
    category: 'HR',
  },
  {
    resource: 'TEACHER',
    action: 'UPDATE',
    permissionString: 'teacher:update',
    description: 'Update teacher academic profile',
    category: 'HR',
  },
  {
    resource: 'TEACHER',
    action: 'DELETE',
    permissionString: 'teacher:delete',
    description: 'Archive teacher academic profile',
    category: 'HR',
  },
  {
    resource: 'DEPARTMENT',
    action: 'CREATE',
    permissionString: 'department:create',
    description: 'Create staff department',
    category: 'HR',
  },
  {
    resource: 'DEPARTMENT',
    action: 'READ',
    permissionString: 'department:read',
    description: 'View staff departments',
    category: 'HR',
  },
  {
    resource: 'DEPARTMENT',
    action: 'UPDATE',
    permissionString: 'department:update',
    description: 'Update staff department details',
    category: 'HR',
  },
  {
    resource: 'DEPARTMENT',
    action: 'DELETE',
    permissionString: 'department:delete',
    description: 'Archive staff department',
    category: 'HR',
  },
  {
    resource: 'DESIGNATION',
    action: 'CREATE',
    permissionString: 'designation:create',
    description: 'Create employee designation',
    category: 'HR',
  },
  {
    resource: 'DESIGNATION',
    action: 'READ',
    permissionString: 'designation:read',
    description: 'View employee designations',
    category: 'HR',
  },
  {
    resource: 'DESIGNATION',
    action: 'UPDATE',
    permissionString: 'designation:update',
    description: 'Update employee designation details',
    category: 'HR',
  },
  {
    resource: 'DESIGNATION',
    action: 'DELETE',
    permissionString: 'designation:delete',
    description: 'Archive employee designation',
    category: 'HR',
  },
  {
    resource: 'LEAVE',
    action: 'APPLY',
    permissionString: 'leave:apply',
    description: 'Submit employee leave request',
    category: 'HR',
  },
  {
    resource: 'LEAVE',
    action: 'APPROVE',
    permissionString: 'leave:approve',
    description: 'Approve or reject leave requests',
    category: 'HR',
  },
  {
    resource: 'EMPLOYEE_HR',
    action: 'READ',
    permissionString: 'employee_hr:read',
    description: 'View employee HR profile and lifecycle details',
    category: 'HR',
  },
  {
    resource: 'EMPLOYEE_HR',
    action: 'UPDATE',
    permissionString: 'employee_hr:update',
    description: 'Update employee HR profile and lifecycle',
    category: 'HR',
  },
  {
    resource: 'EMPLOYEE_HR',
    action: 'MANAGE',
    permissionString: 'employee_hr:manage',
    description: 'Full management of employee HR profile and lifecycle',
    category: 'HR',
  },
  {
    resource: 'EMPLOYEE_DOCUMENTS',
    action: 'READ',
    permissionString: 'employee_documents:read',
    description: 'View employee HR documents',
    category: 'HR',
  },
  {
    resource: 'EMPLOYEE_DOCUMENTS',
    action: 'MANAGE',
    permissionString: 'employee_documents:manage',
    description: 'Upload and manage employee HR documents',
    category: 'HR',
  },
  {
    resource: 'LEAVE_TYPE',
    action: 'MANAGE',
    permissionString: 'leave_type:manage',
    description: 'Manage leave types and allocations',
    category: 'HR',
  },
  {
    resource: 'LEAVE_POLICY',
    action: 'MANAGE',
    permissionString: 'leave_policy:manage',
    description: 'Manage leave policies and rules',
    category: 'HR',
  },
  {
    resource: 'LEAVE_BALANCE',
    action: 'READ',
    permissionString: 'leave_balance:read',
    description: 'View employee leave balances',
    category: 'HR',
  },
  {
    resource: 'LEAVE_APPLICATION',
    action: 'CREATE',
    permissionString: 'leave_application:create',
    description: 'Submit leave applications',
    category: 'HR',
  },
  {
    resource: 'LEAVE_APPLICATION',
    action: 'READ',
    permissionString: 'leave_application:read',
    description: 'View leave applications',
    category: 'HR',
  },
  {
    resource: 'LEAVE_APPLICATION',
    action: 'APPROVE',
    permissionString: 'leave_application:approve',
    description: 'Approve leave applications',
    category: 'HR',
  },
  {
    resource: 'LEAVE_APPLICATION',
    action: 'REJECT',
    permissionString: 'leave_application:reject',
    description: 'Reject leave applications',
    category: 'HR',
  },
  {
    resource: 'LEAVE_APPLICATION',
    action: 'CANCEL',
    permissionString: 'leave_application:cancel',
    description: 'Cancel leave applications',
    category: 'HR',
  },
  {
    resource: 'SALARY_COMPONENT',
    action: 'MANAGE',
    permissionString: 'salary_component:manage',
    description: 'Configure salary earnings and deductions components',
    category: 'HR',
  },
  {
    resource: 'SALARY_STRUCTURE',
    action: 'MANAGE',
    permissionString: 'salary_structure:manage',
    description: 'Create and version salary structures',
    category: 'HR',
  },
  {
    resource: 'EMPLOYEE_SALARY',
    action: 'READ',
    permissionString: 'employee_salary:read',
    description: 'View employee salary assignments and compensation',
    category: 'HR',
  },
  {
    resource: 'EMPLOYEE_SALARY',
    action: 'MANAGE',
    permissionString: 'employee_salary:manage',
    description: 'Assign and update employee salary compensation',
    category: 'HR',
  },
  {
    resource: 'PAYROLL_PERIOD',
    action: 'MANAGE',
    permissionString: 'payroll_period:manage',
    description: 'Create and configure payroll cycles and periods',
    category: 'HR',
  },
  {
    resource: 'PAYROLL',
    action: 'CALCULATE',
    permissionString: 'payroll:calculate',
    description: 'Compute monthly salary runs and net pay',
    category: 'HR',
  },
  {
    resource: 'PAYROLL',
    action: 'REVIEW',
    permissionString: 'payroll:review',
    description: 'Review calculated payroll runs and adjustments',
    category: 'HR',
  },
  {
    resource: 'PAYROLL',
    action: 'APPROVE',
    permissionString: 'payroll:approve',
    description: 'Approve reviewed payroll runs',
    category: 'HR',
  },
  {
    resource: 'PAYROLL',
    action: 'PROCESS',
    permissionString: 'payroll:process',
    description: 'Process and disburse approved payroll',
    category: 'HR',
  },
  {
    resource: 'PAYROLL',
    action: 'LOCK',
    permissionString: 'payroll:lock',
    description: 'Seal and permanently lock processed payroll',
    category: 'HR',
  },
  {
    resource: 'PAYROLL',
    action: 'READ',
    permissionString: 'payroll:read',
    description: 'View payroll runs and employee payroll items',
    category: 'HR',
  },
  {
    resource: 'PAYROLL',
    action: 'REPORT',
    permissionString: 'payroll:report',
    description: 'View HR and payroll reports and analytics',
    category: 'HR',
  },
  {
    resource: 'PAYROLL',
    action: 'DISBURSE',
    permissionString: 'payroll:disburse',
    description: 'Finalize payroll and payouts',
    category: 'HR',
  },
  {
    resource: 'PAYSLIP',
    action: 'READ_OWN',
    permissionString: 'payslip:read_own',
    description: 'View and download own employee payslips',
    category: 'HR',
  },
  {
    resource: 'PAYSLIP',
    action: 'READ',
    permissionString: 'payslip:read',
    description: 'View employee payslips across organization',
    category: 'HR',
  },
  {
    resource: 'PAYSLIP',
    action: 'GENERATE',
    permissionString: 'payslip:generate',
    description: 'Generate and publish official payslips',
    category: 'HR',
  },

  // Facilities & Operations: Library Management
  {
    resource: 'LIBRARY',
    action: 'READ',
    permissionString: 'library:read',
    description: 'View library locations and settings',
    category: 'LIBRARY',
  },
  {
    resource: 'LIBRARY',
    action: 'MANAGE',
    permissionString: 'library:manage',
    description: 'Create and configure library branches and settings',
    category: 'LIBRARY',
  },
  {
    resource: 'BOOK',
    action: 'CREATE',
    permissionString: 'book:create',
    description: 'Create new book titles and catalog entries',
    category: 'LIBRARY',
  },
  {
    resource: 'BOOK',
    action: 'READ',
    permissionString: 'book:read',
    description: 'Search and browse book catalog and bibliographic details',
    category: 'LIBRARY',
  },
  {
    resource: 'BOOK',
    action: 'UPDATE',
    permissionString: 'book:update',
    description: 'Update book catalog details and metadata',
    category: 'LIBRARY',
  },
  {
    resource: 'BOOK',
    action: 'ARCHIVE',
    permissionString: 'book:archive',
    description: 'Archive or deactivate book catalog entries',
    category: 'LIBRARY',
  },
  {
    resource: 'BOOK_COPY',
    action: 'CREATE',
    permissionString: 'book_copy:create',
    description: 'Add physical book copies to library',
    category: 'LIBRARY',
  },
  {
    resource: 'BOOK_COPY',
    action: 'READ',
    permissionString: 'book_copy:read',
    description: 'View book copies, accessions, and shelf locations',
    category: 'LIBRARY',
  },
  {
    resource: 'BOOK_COPY',
    action: 'UPDATE',
    permissionString: 'book_copy:update',
    description: 'Update physical book copy status and condition',
    category: 'LIBRARY',
  },
  {
    resource: 'BOOK_COPY',
    action: 'MANAGE',
    permissionString: 'book_copy:manage',
    description: 'Withdraw, retire, or repair physical book copies',
    category: 'LIBRARY',
  },
  {
    resource: 'LIBRARY_MEMBER',
    action: 'CREATE',
    permissionString: 'library_member:create',
    description: 'Enroll members into the library system',
    category: 'LIBRARY',
  },
  {
    resource: 'LIBRARY_MEMBER',
    action: 'READ',
    permissionString: 'library_member:read',
    description: 'View library memberships and member borrowing profiles',
    category: 'LIBRARY',
  },
  {
    resource: 'LIBRARY_MEMBER',
    action: 'UPDATE',
    permissionString: 'library_member:update',
    description: 'Update library member details and borrowing limits',
    category: 'LIBRARY',
  },
  {
    resource: 'LIBRARY_MEMBER',
    action: 'SUSPEND',
    permissionString: 'library_member:suspend',
    description: 'Suspend or close library memberships',
    category: 'LIBRARY',
  },
  {
    resource: 'CIRCULATION',
    action: 'ISSUE',
    permissionString: 'circulation:issue',
    description: 'Issue book copies to library members',
    category: 'LIBRARY',
  },
  {
    resource: 'CIRCULATION',
    action: 'RETURN',
    permissionString: 'circulation:return',
    description: 'Accept returns and check in book copies',
    category: 'LIBRARY',
  },
  {
    resource: 'CIRCULATION',
    action: 'RENEW',
    permissionString: 'circulation:renew',
    description: 'Renew active book loans',
    category: 'LIBRARY',
  },
  {
    resource: 'CIRCULATION',
    action: 'READ',
    permissionString: 'circulation:read',
    description: 'View active and historical circulation records',
    category: 'LIBRARY',
  },
  {
    resource: 'RESERVATION',
    action: 'CREATE',
    permissionString: 'reservation:create',
    description: 'Place holds and reserve book titles',
    category: 'LIBRARY',
  },
  {
    resource: 'RESERVATION',
    action: 'READ',
    permissionString: 'reservation:read',
    description: 'View pending and fulfilled book reservations',
    category: 'LIBRARY',
  },
  {
    resource: 'RESERVATION',
    action: 'MANAGE',
    permissionString: 'reservation:manage',
    description: 'Fulfill, cancel, or prioritize book reservations',
    category: 'LIBRARY',
  },
  {
    resource: 'FINE',
    action: 'READ',
    permissionString: 'fine:read',
    description: 'View library fines, dues, and payment histories',
    category: 'LIBRARY',
  },
  {
    resource: 'FINE',
    action: 'ASSESS',
    permissionString: 'fine:assess',
    description: 'Assess overdue and book damage penalties',
    category: 'LIBRARY',
  },
  {
    resource: 'FINE',
    action: 'WAIVE',
    permissionString: 'fine:waive',
    description: 'Grant authorized waivers on outstanding library fines',
    category: 'LIBRARY',
  },
  {
    resource: 'FINE',
    action: 'SETTLE',
    permissionString: 'fine:settle',
    description: 'Collect and settle library fines',
    category: 'LIBRARY',
  },
  {
    resource: 'LIBRARY_REPORT',
    action: 'READ',
    permissionString: 'library_report:read',
    description: 'Generate library circulation, inventory, and fine reports',
    category: 'LIBRARY',
  },
  // =========================================================================
  // Phase 16: Transport Management Permissions
  // =========================================================================
  {
    resource: 'TRANSPORT',
    action: 'READ',
    permissionString: 'transport:read',
    description: 'View transport dashboard, vehicles, routes, and schedules',
    category: 'TRANSPORT',
  },
  {
    resource: 'TRANSPORT',
    action: 'MANAGE',
    permissionString: 'transport:manage',
    description: 'Manage full transport operations, fleet, and routing',
    category: 'TRANSPORT',
  },
  {
    resource: 'TRANSPORT',
    action: 'SETTINGS',
    permissionString: 'transport:settings',
    description: 'Configure transport policies and operational thresholds',
    category: 'TRANSPORT',
  },
  {
    resource: 'VEHICLE',
    action: 'CREATE',
    permissionString: 'vehicle:create',
    description: 'Register new vehicles into the fleet',
    category: 'TRANSPORT',
  },
  {
    resource: 'VEHICLE',
    action: 'READ',
    permissionString: 'vehicle:read',
    description: 'View vehicle inventory, specifications, and status',
    category: 'TRANSPORT',
  },
  {
    resource: 'VEHICLE',
    action: 'UPDATE',
    permissionString: 'vehicle:update',
    description: 'Update vehicle information, assignments, and documents',
    category: 'TRANSPORT',
  },
  {
    resource: 'VEHICLE',
    action: 'ARCHIVE',
    permissionString: 'vehicle:archive',
    description: 'Retire or archive vehicles from active service',
    category: 'TRANSPORT',
  },
  {
    resource: 'VEHICLE',
    action: 'MAINTENANCE',
    permissionString: 'vehicle:maintenance',
    description: 'Log and complete vehicle maintenance and service orders',
    category: 'TRANSPORT',
  },
  {
    resource: 'VEHICLE',
    action: 'INSPECT',
    permissionString: 'vehicle:inspect',
    description: 'Perform safety inspections and checklists on vehicles',
    category: 'TRANSPORT',
  },
  {
    resource: 'ROUTE',
    action: 'CREATE',
    permissionString: 'route:create',
    description: 'Design and create transport routes and stops',
    category: 'TRANSPORT',
  },
  {
    resource: 'ROUTE',
    action: 'READ',
    permissionString: 'route:read',
    description: 'View transport routes, stops, and schedules',
    category: 'TRANSPORT',
  },
  {
    resource: 'ROUTE',
    action: 'UPDATE',
    permissionString: 'route:update',
    description: 'Modify route details, stop sequences, and timings',
    category: 'TRANSPORT',
  },
  {
    resource: 'ROUTE',
    action: 'ARCHIVE',
    permissionString: 'route:archive',
    description: 'Deactivate or archive transport routes',
    category: 'TRANSPORT',
  },
  {
    resource: 'ROUTE',
    action: 'MANAGE',
    permissionString: 'route:manage',
    description: 'Publish route versions and manage route capacity',
    category: 'TRANSPORT',
  },
  {
    resource: 'DRIVER',
    action: 'READ',
    permissionString: 'driver:read',
    description: 'View drivers and attendants profiles and licenses',
    category: 'TRANSPORT',
  },
  {
    resource: 'DRIVER',
    action: 'MANAGE',
    permissionString: 'driver:manage',
    description: 'Manage driver profiles, licenses, and verifications',
    category: 'TRANSPORT',
  },
  {
    resource: 'DRIVER',
    action: 'ASSIGN',
    permissionString: 'driver:assign',
    description: 'Assign drivers and attendants to vehicles and routes',
    category: 'TRANSPORT',
  },
  {
    resource: 'TRANSPORT_ASSIGNMENT',
    action: 'CREATE',
    permissionString: 'transport_assignment:create',
    description: 'Assign students to transport routes and stops',
    category: 'TRANSPORT',
  },
  {
    resource: 'TRANSPORT_ASSIGNMENT',
    action: 'READ',
    permissionString: 'transport_assignment:read',
    description: 'View student transport assignments and seat allocations',
    category: 'TRANSPORT',
  },
  {
    resource: 'TRANSPORT_ASSIGNMENT',
    action: 'UPDATE',
    permissionString: 'transport_assignment:update',
    description: 'Modify student pickup/drop stops and routes',
    category: 'TRANSPORT',
  },
  {
    resource: 'TRANSPORT_ASSIGNMENT',
    action: 'CANCEL',
    permissionString: 'transport_assignment:cancel',
    description: 'Cancel or suspend student transport service',
    category: 'TRANSPORT',
  },
  {
    resource: 'TRIP',
    action: 'CREATE',
    permissionString: 'trip:create',
    description: 'Schedule and generate morning/afternoon trips',
    category: 'TRANSPORT',
  },
  {
    resource: 'TRIP',
    action: 'READ',
    permissionString: 'trip:read',
    description: 'View trip rosters, live statuses, and schedules',
    category: 'TRANSPORT',
  },
  {
    resource: 'TRIP',
    action: 'START',
    permissionString: 'trip:start',
    description: 'Start scheduled trips and commence journey tracking',
    category: 'TRANSPORT',
  },
  {
    resource: 'TRIP',
    action: 'UPDATE',
    permissionString: 'trip:update',
    description: 'Update trip details, delays, and notes',
    category: 'TRANSPORT',
  },
  {
    resource: 'TRIP',
    action: 'COMPLETE',
    permissionString: 'trip:complete',
    description: 'Complete trips and close out transport runs',
    category: 'TRANSPORT',
  },
  {
    resource: 'TRIP',
    action: 'CANCEL',
    permissionString: 'trip:cancel',
    description: 'Cancel scheduled trips with logged reasons',
    category: 'TRANSPORT',
  },
  {
    resource: 'TRIP_ATTENDANCE',
    action: 'READ',
    permissionString: 'trip_attendance:read',
    description: 'View student boarding and drop statuses for trips',
    category: 'TRANSPORT',
  },
  {
    resource: 'TRIP_ATTENDANCE',
    action: 'MANAGE',
    permissionString: 'trip_attendance:manage',
    description: 'Mark student boarding, absent, or drop events',
    category: 'TRANSPORT',
  },
  {
    resource: 'TRANSPORT_INCIDENT',
    action: 'CREATE',
    permissionString: 'transport_incident:create',
    description: 'Report breakdowns, accidents, or delays',
    category: 'TRANSPORT',
  },
  {
    resource: 'TRANSPORT_INCIDENT',
    action: 'READ',
    permissionString: 'transport_incident:read',
    description: 'View reported transport incidents and logs',
    category: 'TRANSPORT',
  },
  {
    resource: 'TRANSPORT_INCIDENT',
    action: 'MANAGE',
    permissionString: 'transport_incident:manage',
    description: 'Investigate and update transport incidents',
    category: 'TRANSPORT',
  },
  {
    resource: 'TRANSPORT_INCIDENT',
    action: 'RESOLVE',
    permissionString: 'transport_incident:resolve',
    description: 'Resolve and close investigated transport incidents',
    category: 'TRANSPORT',
  },
  {
    resource: 'TRANSPORT_REPORT',
    action: 'READ',
    permissionString: 'transport_report:read',
    description: 'Generate fleet, utilization, incident, and fee reports',
    category: 'TRANSPORT',
  },
  // Legacy alias permissions
  {
    resource: 'LIBRARY',
    action: 'CATALOG',
    permissionString: 'library:catalog',
    description: 'Manage library catalog and book copies',
    category: 'FACILITIES',
  },
  {
    resource: 'LIBRARY',
    action: 'CIRCULATION',
    permissionString: 'library:circulation',
    description: 'Issue, return, and fine library books',
    category: 'FACILITIES',
  },
  {
    resource: 'TRANSPORT',
    action: 'FLEET',
    permissionString: 'transport:fleet',
    description: 'Manage buses, vans, and drivers',
    category: 'FACILITIES',
  },
  {
    resource: 'TRANSPORT',
    action: 'ASSIGN',
    permissionString: 'transport:assign',
    description: 'Assign routes and stops to students',
    category: 'FACILITIES',
  },
  {
    resource: 'HOSTEL',
    action: 'READ',
    permissionString: 'hostel:read',
    description: 'View hostel information, rooms, and assignments',
    category: 'FACILITIES',
  },
  {
    resource: 'HOSTEL',
    action: 'MANAGE',
    permissionString: 'hostel:manage',
    description: 'Manage hostels, buildings, rooms, and beds',
    category: 'FACILITIES',
  },
  {
    resource: 'HOSTEL',
    action: 'SETTINGS',
    permissionString: 'hostel:settings',
    description: 'Configure hostel policies, curfew, and fee settings',
    category: 'FACILITIES',
  },
  {
    resource: 'HOSTEL_BUILDING',
    action: 'MANAGE',
    permissionString: 'hostel_building:manage',
    description: 'Create and configure hostel buildings and floors',
    category: 'FACILITIES',
  },
  {
    resource: 'HOSTEL_ROOM',
    action: 'MANAGE',
    permissionString: 'hostel_room:manage',
    description: 'Manage hostel rooms and room types',
    category: 'FACILITIES',
  },
  {
    resource: 'HOSTEL_BED',
    action: 'MANAGE',
    permissionString: 'hostel_bed:manage',
    description: 'Manage physical beds, block/unblock beds',
    category: 'FACILITIES',
  },
  {
    resource: 'HOSTEL_ALLOCATION',
    action: 'CREATE',
    permissionString: 'hostel_allocation:create',
    description: 'Allocate hostel rooms and beds to students',
    category: 'FACILITIES',
  },
  {
    resource: 'HOSTEL_ALLOCATION',
    action: 'READ',
    permissionString: 'hostel_allocation:read',
    description: 'View student hostel allocations',
    category: 'FACILITIES',
  },
  {
    resource: 'HOSTEL_ALLOCATION',
    action: 'UPDATE',
    permissionString: 'hostel_allocation:update',
    description: 'Update student hostel allocations and check-in',
    category: 'FACILITIES',
  },
  {
    resource: 'HOSTEL_ALLOCATION',
    action: 'TRANSFER',
    permissionString: 'hostel_allocation:transfer',
    description: 'Transfer students between hostel rooms and beds',
    category: 'FACILITIES',
  },
  {
    resource: 'HOSTEL_ALLOCATION',
    action: 'CHECKOUT',
    permissionString: 'hostel_allocation:checkout',
    description: 'Process student hostel checkout and clearance',
    category: 'FACILITIES',
  },
  {
    resource: 'HOSTEL_ATTENDANCE',
    action: 'READ',
    permissionString: 'hostel_attendance:read',
    description: 'View residential hostel attendance registers',
    category: 'FACILITIES',
  },
  {
    resource: 'HOSTEL_ATTENDANCE',
    action: 'MANAGE',
    permissionString: 'hostel_attendance:manage',
    description: 'Mark and submit residential hostel attendance',
    category: 'FACILITIES',
  },
  {
    resource: 'HOSTEL_OUTING',
    action: 'CREATE',
    permissionString: 'hostel_outing:create',
    description: 'Request or log student hostel outing/leave',
    category: 'FACILITIES',
  },
  {
    resource: 'HOSTEL_OUTING',
    action: 'READ',
    permissionString: 'hostel_outing:read',
    description: 'View student hostel outings and return logs',
    category: 'FACILITIES',
  },
  {
    resource: 'HOSTEL_OUTING',
    action: 'APPROVE',
    permissionString: 'hostel_outing:approve',
    description: 'Approve or reject student hostel outings',
    category: 'FACILITIES',
  },
  {
    resource: 'HOSTEL_OUTING',
    action: 'MANAGE',
    permissionString: 'hostel_outing:manage',
    description: 'Mark student outing departure and return',
    category: 'FACILITIES',
  },
  {
    resource: 'HOSTEL_INCIDENT',
    action: 'CREATE',
    permissionString: 'hostel_incident:create',
    description: 'Report hostel safety or disciplinary incident',
    category: 'FACILITIES',
  },
  {
    resource: 'HOSTEL_INCIDENT',
    action: 'READ',
    permissionString: 'hostel_incident:read',
    description: 'View hostel incident reports',
    category: 'FACILITIES',
  },
  {
    resource: 'HOSTEL_INCIDENT',
    action: 'MANAGE',
    permissionString: 'hostel_incident:manage',
    description: 'Investigate and manage hostel incidents',
    category: 'FACILITIES',
  },
  {
    resource: 'HOSTEL_INCIDENT',
    action: 'RESOLVE',
    permissionString: 'hostel_incident:resolve',
    description: 'Resolve and close hostel incidents',
    category: 'FACILITIES',
  },
  {
    resource: 'HOSTEL_MAINTENANCE',
    action: 'CREATE',
    permissionString: 'hostel_maintenance:create',
    description: 'Create hostel maintenance and repair requests',
    category: 'FACILITIES',
  },
  {
    resource: 'HOSTEL_MAINTENANCE',
    action: 'READ',
    permissionString: 'hostel_maintenance:read',
    description: 'View hostel maintenance requests and logs',
    category: 'FACILITIES',
  },
  {
    resource: 'HOSTEL_MAINTENANCE',
    action: 'MANAGE',
    permissionString: 'hostel_maintenance:manage',
    description: 'Assign, update, and resolve hostel maintenance',
    category: 'FACILITIES',
  },
  {
    resource: 'HOSTEL_REPORT',
    action: 'READ',
    permissionString: 'hostel_report:read',
    description: 'View hostel occupancy, attendance, and fee reports',
    category: 'FACILITIES',
  },
  {
    resource: 'INVENTORY',
    action: 'READ',
    permissionString: 'inventory:read',
    description: 'View inventory dashboard and general stock levels',
    category: 'FACILITIES',
  },
  {
    resource: 'INVENTORY',
    action: 'MANAGE',
    permissionString: 'inventory:manage',
    description: 'Manage inventory settings and operations',
    category: 'FACILITIES',
  },
  {
    resource: 'INVENTORY_ITEM',
    action: 'CREATE',
    permissionString: 'inventory_item:create',
    description: 'Create catalog inventory items',
    category: 'FACILITIES',
  },
  {
    resource: 'INVENTORY_ITEM',
    action: 'READ',
    permissionString: 'inventory_item:read',
    description: 'View catalog inventory items and details',
    category: 'FACILITIES',
  },
  {
    resource: 'INVENTORY_ITEM',
    action: 'UPDATE',
    permissionString: 'inventory_item:update',
    description: 'Update catalog inventory items',
    category: 'FACILITIES',
  },
  {
    resource: 'INVENTORY_ITEM',
    action: 'ARCHIVE',
    permissionString: 'inventory_item:archive',
    description: 'Archive or deactivate inventory items',
    category: 'FACILITIES',
  },
  {
    resource: 'INVENTORY_STORE',
    action: 'CREATE',
    permissionString: 'inventory_store:create',
    description: 'Create inventory stores and warehouses',
    category: 'FACILITIES',
  },
  {
    resource: 'INVENTORY_STORE',
    action: 'READ',
    permissionString: 'inventory_store:read',
    description: 'View inventory stores and locations',
    category: 'FACILITIES',
  },
  {
    resource: 'INVENTORY_STORE',
    action: 'UPDATE',
    permissionString: 'inventory_store:update',
    description: 'Update inventory stores and locations',
    category: 'FACILITIES',
  },
  {
    resource: 'INVENTORY_STORE',
    action: 'MANAGE',
    permissionString: 'inventory_store:manage',
    description: 'Manage inventory stores, aisles, racks, and bins',
    category: 'FACILITIES',
  },
  {
    resource: 'INVENTORY_SUPPLIER',
    action: 'MANAGE',
    permissionString: 'inventory_supplier:manage',
    description: 'Create and manage suppliers and vendors',
    category: 'FACILITIES',
  },
  {
    resource: 'INVENTORY_SUPPLIER',
    action: 'READ',
    permissionString: 'inventory_supplier:read',
    description: 'View suppliers and vendor directory',
    category: 'FACILITIES',
  },
  {
    resource: 'STOCK',
    action: 'READ',
    permissionString: 'stock:read',
    description: 'View stock balances, batches, and movements',
    category: 'FACILITIES',
  },
  {
    resource: 'STOCK',
    action: 'RECEIVE',
    permissionString: 'stock:receive',
    description: 'Receive stock shipments from suppliers and create receipts',
    category: 'FACILITIES',
  },
  {
    resource: 'STOCK',
    action: 'ISSUE',
    permissionString: 'stock:issue',
    description: 'Issue stock items to departments, staff, or classrooms',
    category: 'FACILITIES',
  },
  {
    resource: 'STOCK',
    action: 'RETURN',
    permissionString: 'stock:return',
    description: 'Process returns of issued stock items',
    category: 'FACILITIES',
  },
  {
    resource: 'STOCK',
    action: 'TRANSFER',
    permissionString: 'stock:transfer',
    description: 'Request, approve, dispatch, and receive inter-store stock transfers',
    category: 'FACILITIES',
  },
  {
    resource: 'STOCK',
    action: 'ADJUST',
    permissionString: 'stock:adjust',
    description: 'Perform stock adjustments and write-offs',
    category: 'FACILITIES',
  },
  {
    resource: 'STOCK',
    action: 'RESERVE',
    permissionString: 'stock:reserve',
    description: 'Reserve stock quantities for upcoming allocations',
    category: 'FACILITIES',
  },
  {
    resource: 'STOCKTAKE',
    action: 'CREATE',
    permissionString: 'stocktake:create',
    description: 'Initiate physical inventory stocktake count sessions',
    category: 'FACILITIES',
  },
  {
    resource: 'STOCKTAKE',
    action: 'READ',
    permissionString: 'stocktake:read',
    description: 'View physical inventory stocktake count sessions and variances',
    category: 'FACILITIES',
  },
  {
    resource: 'STOCKTAKE',
    action: 'APPROVE',
    permissionString: 'stocktake:approve',
    description: 'Approve stocktake count variances and reconcile stock',
    category: 'FACILITIES',
  },
  {
    resource: 'STOCKTAKE',
    action: 'CLOSE',
    permissionString: 'stocktake:close',
    description: 'Finalize and close inventory stocktake audits',
    category: 'FACILITIES',
  },
  {
    resource: 'ASSET',
    action: 'CREATE',
    permissionString: 'asset:create',
    description: 'Register new durable assets with serials and asset tags',
    category: 'FACILITIES',
  },
  {
    resource: 'ASSET',
    action: 'READ',
    permissionString: 'asset:read',
    description: 'View durable assets, warranty, and location records',
    category: 'FACILITIES',
  },
  {
    resource: 'ASSET',
    action: 'UPDATE',
    permissionString: 'asset:update',
    description: 'Update asset specifications, status, and condition',
    category: 'FACILITIES',
  },
  {
    resource: 'ASSET',
    action: 'ASSIGN',
    permissionString: 'asset:assign',
    description: 'Assign assets to employees, departments, or classrooms',
    category: 'FACILITIES',
  },
  {
    resource: 'ASSET',
    action: 'RETURN',
    permissionString: 'asset:return',
    description: 'Process return of assigned assets and verify condition',
    category: 'FACILITIES',
  },
  {
    resource: 'ASSET',
    action: 'TRANSFER',
    permissionString: 'asset:transfer',
    description: 'Transfer assets between assignees or store locations',
    category: 'FACILITIES',
  },
  {
    resource: 'ASSET',
    action: 'MAINTENANCE',
    permissionString: 'asset:maintenance',
    description: 'Log and track asset repairs, maintenance, and service costs',
    category: 'FACILITIES',
  },
  {
    resource: 'ASSET',
    action: 'DISPOSE',
    permissionString: 'asset:dispose',
    description: 'Decommission and dispose of obsolete or damaged assets',
    category: 'FACILITIES',
  },
  {
    resource: 'INVENTORY_REPORT',
    action: 'READ',
    permissionString: 'inventory_report:read',
    description: 'View stock valuation, ledger, and asset audit reports',
    category: 'FACILITIES',
  },
  {
    resource: 'ANNOUNCEMENT',
    action: 'PUBLISH',
    permissionString: 'announcement:publish',
    description: 'Broadcast school-wide announcements',
    category: 'COMMUNICATION',
  },
  {
    resource: 'NOTIFICATION',
    action: 'READ',
    permissionString: 'notification:read',
    description: 'View in-app notifications and unread counters',
    category: 'COMMUNICATION',
  },
  {
    resource: 'NOTIFICATION',
    action: 'MANAGE',
    permissionString: 'notification:manage',
    description: 'Full administrative control over notification records',
    category: 'COMMUNICATION',
  },
  {
    resource: 'NOTIFICATION_TEMPLATE',
    action: 'CREATE',
    permissionString: 'notification_template:create',
    description: 'Create notification message templates',
    category: 'COMMUNICATION',
  },
  {
    resource: 'NOTIFICATION_TEMPLATE',
    action: 'READ',
    permissionString: 'notification_template:read',
    description: 'View notification templates and variables',
    category: 'COMMUNICATION',
  },
  {
    resource: 'NOTIFICATION_TEMPLATE',
    action: 'UPDATE',
    permissionString: 'notification_template:update',
    description: 'Edit notification templates and draft versions',
    category: 'COMMUNICATION',
  },
  {
    resource: 'NOTIFICATION_TEMPLATE',
    action: 'PUBLISH',
    permissionString: 'notification_template:publish',
    description: 'Publish notification templates for active event triggers',
    category: 'COMMUNICATION',
  },
  {
    resource: 'NOTIFICATION_TEMPLATE',
    action: 'ARCHIVE',
    permissionString: 'notification_template:archive',
    description: 'Archive obsolete notification templates',
    category: 'COMMUNICATION',
  },
  {
    resource: 'ANNOUNCEMENT',
    action: 'CREATE',
    permissionString: 'announcement:create',
    description: 'Draft school announcements and broadcasts',
    category: 'COMMUNICATION',
  },
  {
    resource: 'ANNOUNCEMENT',
    action: 'READ',
    permissionString: 'announcement:read',
    description: 'View school and campus announcements',
    category: 'COMMUNICATION',
  },
  {
    resource: 'ANNOUNCEMENT',
    action: 'UPDATE',
    permissionString: 'announcement:update',
    description: 'Edit scheduled and draft announcements',
    category: 'COMMUNICATION',
  },
  {
    resource: 'ANNOUNCEMENT',
    action: 'CANCEL',
    permissionString: 'announcement:cancel',
    description: 'Cancel scheduled or active announcements',
    category: 'COMMUNICATION',
  },
  {
    resource: 'ANNOUNCEMENT',
    action: 'ARCHIVE',
    permissionString: 'announcement:archive',
    description: 'Archive expired announcements',
    category: 'COMMUNICATION',
  },
  {
    resource: 'COMMUNICATION',
    action: 'CREATE',
    permissionString: 'communication:create',
    description: 'Create targeted communication campaigns',
    category: 'COMMUNICATION',
  },
  {
    resource: 'COMMUNICATION',
    action: 'READ',
    permissionString: 'communication:read',
    description: 'View communication jobs and history',
    category: 'COMMUNICATION',
  },
  {
    resource: 'COMMUNICATION',
    action: 'SEND',
    permissionString: 'communication:send',
    description: 'Dispatch asynchronous bulk communications',
    category: 'COMMUNICATION',
  },
  {
    resource: 'COMMUNICATION',
    action: 'CANCEL',
    permissionString: 'communication:cancel',
    description: 'Halt pending communication jobs',
    category: 'COMMUNICATION',
  },
  {
    resource: 'NOTIFICATION_PREFERENCE',
    action: 'READ',
    permissionString: 'notification_preference:read',
    description: 'View user notification and quiet hours preferences',
    category: 'COMMUNICATION',
  },
  {
    resource: 'NOTIFICATION_PREFERENCE',
    action: 'UPDATE',
    permissionString: 'notification_preference:update',
    description: 'Configure notification channels and quiet hours',
    category: 'COMMUNICATION',
  },
  {
    resource: 'NOTIFICATION_DELIVERY',
    action: 'READ',
    permissionString: 'notification_delivery:read',
    description: 'Inspect per-channel delivery logs and status',
    category: 'COMMUNICATION',
  },
  {
    resource: 'NOTIFICATION_DELIVERY',
    action: 'RETRY',
    permissionString: 'notification_delivery:retry',
    description: 'Trigger retry for failed notification deliveries',
    category: 'COMMUNICATION',
  },
  {
    resource: 'COMMUNICATION_REPORT',
    action: 'READ',
    permissionString: 'communication_report:read',
    description: 'View communication analytics and delivery reports',
    category: 'COMMUNICATION',
  },
];
