export interface PermissionSeedItem {
  resource: string;
  action: string;
  permissionString: string;
  description: string;
  category: string;
}

export const SYSTEM_PERMISSIONS: PermissionSeedItem[] = [
  // Tenant & System (5)
  {
    resource: 'TENANT',
    action: 'CREATE',
    permissionString: 'tenant:create',
    description: 'Create new tenant subscribers',
    category: 'SYSTEM',
  },
  {
    resource: 'TENANT',
    action: 'READ',
    permissionString: 'tenant:read',
    description: 'View tenant details',
    category: 'SYSTEM',
  },
  {
    resource: 'TENANT',
    action: 'UPDATE',
    permissionString: 'tenant:update',
    description: 'Update tenant config',
    category: 'SYSTEM',
  },
  {
    resource: 'TENANT',
    action: 'DELETE',
    permissionString: 'tenant:delete',
    description: 'Deactivate tenant',
    category: 'SYSTEM',
  },
  {
    resource: 'AUDIT',
    action: 'READ',
    permissionString: 'audit:read',
    description: 'Read system audit trail',
    category: 'SYSTEM',
  },

  // School & Campus Configuration
  {
    resource: 'SCHOOL',
    action: 'CREATE',
    permissionString: 'school:create',
    description: 'Create schools',
    category: 'ACADEMIC',
  },
  {
    resource: 'SCHOOL',
    action: 'READ',
    permissionString: 'school:read',
    description: 'View schools',
    category: 'ACADEMIC',
  },
  {
    resource: 'SCHOOL',
    action: 'UPDATE',
    permissionString: 'school:update',
    description: 'Update school details',
    category: 'ACADEMIC',
  },
  {
    resource: 'CAMPUS',
    action: 'CREATE',
    permissionString: 'campus:create',
    description: 'Create new campus sites',
    category: 'ACADEMIC',
  },
  {
    resource: 'CAMPUS',
    action: 'READ',
    permissionString: 'campus:read',
    description: 'View campus sites',
    category: 'ACADEMIC',
  },
  {
    resource: 'CAMPUS',
    action: 'UPDATE',
    permissionString: 'campus:update',
    description: 'Update campus details',
    category: 'ACADEMIC',
  },
  {
    resource: 'CAMPUS',
    action: 'DELETE',
    permissionString: 'campus:delete',
    description: 'Archive or deactivate campus sites',
    category: 'ACADEMIC',
  },
  {
    resource: 'CAMPUS',
    action: 'MANAGE',
    permissionString: 'campus:manage',
    description: 'Manage campus sites',
    category: 'ACADEMIC',
  },
  {
    resource: 'ACADEMIC_YEAR',
    action: 'CREATE',
    permissionString: 'academic_year:create',
    description: 'Create academic years',
    category: 'ACADEMIC',
  },
  {
    resource: 'ACADEMIC_YEAR',
    action: 'READ',
    permissionString: 'academic_year:read',
    description: 'View academic calendars',
    category: 'ACADEMIC',
  },
  {
    resource: 'ACADEMIC_YEAR',
    action: 'UPDATE',
    permissionString: 'academic_year:update',
    description: 'Update academic calendar details',
    category: 'ACADEMIC',
  },
  {
    resource: 'ACADEMIC_YEAR',
    action: 'ACTIVATE',
    permissionString: 'academic_year:activate',
    description: 'Activate academic year and set as current session',
    category: 'ACADEMIC',
  },
  {
    resource: 'ACADEMIC_YEAR',
    action: 'CLOSE',
    permissionString: 'academic_year:close',
    description: 'Close academic year session',
    category: 'ACADEMIC',
  },
  {
    resource: 'ACADEMIC_YEAR',
    action: 'MANAGE',
    permissionString: 'academic_year:manage',
    description: 'Manage academic calendars',
    category: 'ACADEMIC',
  },
  {
    resource: 'SETTINGS',
    action: 'READ',
    permissionString: 'settings:read',
    description: 'View school operational settings',
    category: 'ACADEMIC',
  },
  {
    resource: 'SETTINGS',
    action: 'UPDATE',
    permissionString: 'settings:update',
    description: 'Update school operational settings',
    category: 'ACADEMIC',
  },
  {
    resource: 'BRANDING',
    action: 'READ',
    permissionString: 'branding:read',
    description: 'View school branding assets',
    category: 'ACADEMIC',
  },
  {
    resource: 'BRANDING',
    action: 'UPDATE',
    permissionString: 'branding:update',
    description: 'Update school branding assets and display themes',
    category: 'ACADEMIC',
  },
  {
    resource: 'RBAC',
    action: 'MANAGE',
    permissionString: 'rbac:manage',
    description: 'Manage roles and permissions',
    category: 'SYSTEM',
  },

  // Academic Structure & Curriculum (8)
  {
    resource: 'CLASS',
    action: 'MANAGE',
    permissionString: 'class:manage',
    description: 'Create and edit grades/classes',
    category: 'ACADEMIC',
  },
  {
    resource: 'SECTION',
    action: 'MANAGE',
    permissionString: 'section:manage',
    description: 'Create and configure class divisions',
    category: 'ACADEMIC',
  },
  {
    resource: 'SUBJECT',
    action: 'MANAGE',
    permissionString: 'subject:manage',
    description: 'Manage curriculum subjects',
    category: 'ACADEMIC',
  },
  {
    resource: 'TEACHER_ASSIGNMENT',
    action: 'MANAGE',
    permissionString: 'teacher_assignment:manage',
    description: 'Assign teachers to subjects/sections',
    category: 'ACADEMIC',
  },
  {
    resource: 'TIMETABLE',
    action: 'CREATE',
    permissionString: 'timetable:create',
    description: 'Generate schedule timetable',
    category: 'ACADEMIC',
  },
  {
    resource: 'TIMETABLE',
    action: 'READ',
    permissionString: 'timetable:read',
    description: 'View schedule timetable',
    category: 'ACADEMIC',
  },
  {
    resource: 'TIMETABLE',
    action: 'UPDATE',
    permissionString: 'timetable:update',
    description: 'Modify schedule timetable',
    category: 'ACADEMIC',
  },
  {
    resource: 'TIMETABLE',
    action: 'PUBLISH',
    permissionString: 'timetable:publish',
    description: 'Publish timetable to students/teachers',
    category: 'ACADEMIC',
  },

  // Student & Admissions (11)
  {
    resource: 'STUDENT',
    action: 'CREATE',
    permissionString: 'student:create',
    description: 'Register new student profile',
    category: 'STUDENT',
  },
  {
    resource: 'STUDENT',
    action: 'READ',
    permissionString: 'student:read',
    description: 'View student profile and records',
    category: 'STUDENT',
  },
  {
    resource: 'STUDENT',
    action: 'UPDATE',
    permissionString: 'student:update',
    description: 'Modify student profile',
    category: 'STUDENT',
  },
  {
    resource: 'STUDENT',
    action: 'DELETE',
    permissionString: 'student:delete',
    description: 'Archive or soft delete student profile',
    category: 'STUDENT',
  },
  {
    resource: 'STUDENT',
    action: 'PROMOTE',
    permissionString: 'student:promote',
    description: 'Promote student to next academic grade',
    category: 'STUDENT',
  },
  {
    resource: 'STUDENT',
    action: 'TRANSFER',
    permissionString: 'student:transfer',
    description: 'Transfer or issue TC to student',
    category: 'STUDENT',
  },
  {
    resource: 'ADMISSION',
    action: 'CREATE',
    permissionString: 'admission:create',
    description: 'Submit admission application',
    category: 'ADMISSION',
  },
  {
    resource: 'ADMISSION',
    action: 'READ',
    permissionString: 'admission:read',
    description: 'View admission applications',
    category: 'ADMISSION',
  },
  {
    resource: 'ADMISSION',
    action: 'REVIEW',
    permissionString: 'admission:review',
    description: 'Review and verify applicant documents',
    category: 'ADMISSION',
  },
  {
    resource: 'ADMISSION',
    action: 'APPROVE',
    permissionString: 'admission:approve',
    description: 'Grant official admission approval',
    category: 'ADMISSION',
  },
  {
    resource: 'ADMISSION',
    action: 'REJECT',
    permissionString: 'admission:reject',
    description: 'Reject admission application',
    category: 'ADMISSION',
  },

  // Attendance & Classroom (7)
  {
    resource: 'ATTENDANCE',
    action: 'MARK',
    permissionString: 'attendance:mark',
    description: 'Submit daily attendance for students',
    category: 'ATTENDANCE',
  },
  {
    resource: 'ATTENDANCE',
    action: 'READ',
    permissionString: 'attendance:read',
    description: 'View student attendance records',
    category: 'ATTENDANCE',
  },
  {
    resource: 'ATTENDANCE',
    action: 'UPDATE',
    permissionString: 'attendance:update',
    description: 'Correct previously submitted attendance',
    category: 'ATTENDANCE',
  },
  {
    resource: 'ATTENDANCE',
    action: 'LOCK',
    permissionString: 'attendance:lock',
    description: 'Lock attendance registers against editing',
    category: 'ATTENDANCE',
  },
  {
    resource: 'ATTENDANCE',
    action: 'EXPORT',
    permissionString: 'attendance:export',
    description: 'Download attendance reports',
    category: 'ATTENDANCE',
  },
  {
    resource: 'STAFF_ATTENDANCE',
    action: 'MARK',
    permissionString: 'staff_attendance:mark',
    description: 'Record employee attendance',
    category: 'HR',
  },
  {
    resource: 'STAFF_ATTENDANCE',
    action: 'READ',
    permissionString: 'staff_attendance:read',
    description: 'View employee attendance logs',
    category: 'HR',
  },

  // Homework & Assignments (5)
  {
    resource: 'HOMEWORK',
    action: 'CREATE',
    permissionString: 'homework:create',
    description: 'Publish homework assignments',
    category: 'ACADEMIC',
  },
  {
    resource: 'HOMEWORK',
    action: 'READ',
    permissionString: 'homework:read',
    description: 'View assigned homework',
    category: 'ACADEMIC',
  },
  {
    resource: 'HOMEWORK',
    action: 'UPDATE',
    permissionString: 'homework:update',
    description: 'Edit homework details and due date',
    category: 'ACADEMIC',
  },
  {
    resource: 'HOMEWORK',
    action: 'GRADE',
    permissionString: 'homework:grade',
    description: 'Grade and provide feedback on submissions',
    category: 'ACADEMIC',
  },
  {
    resource: 'HOMEWORK',
    action: 'SUBMIT',
    permissionString: 'homework:submit',
    description: 'Upload completed homework solution',
    category: 'ACADEMIC',
  },

  // Examinations & Grading (9)
  {
    resource: 'EXAM',
    action: 'CREATE',
    permissionString: 'exam:create',
    description: 'Configure examination cycles',
    category: 'EXAMINATION',
  },
  {
    resource: 'EXAM',
    action: 'READ',
    permissionString: 'exam:read',
    description: 'View exam details',
    category: 'EXAMINATION',
  },
  {
    resource: 'EXAM',
    action: 'SCHEDULE',
    permissionString: 'exam:schedule',
    description: 'Schedule exam timetable and rooms',
    category: 'EXAMINATION',
  },
  {
    resource: 'EXAM',
    action: 'PUBLISH',
    permissionString: 'exam:publish',
    description: 'Publish examination timetables',
    category: 'EXAMINATION',
  },
  {
    resource: 'EXAM',
    action: 'LOCK',
    permissionString: 'exam:lock',
    description: 'Lock completed examination entries',
    category: 'EXAMINATION',
  },
  {
    resource: 'MARKS',
    action: 'ENTRY',
    permissionString: 'marks:entry',
    description: 'Input student marks for subject',
    category: 'EXAMINATION',
  },
  {
    resource: 'MARKS',
    action: 'VERIFY',
    permissionString: 'marks:verify',
    description: 'Verify and approve grade sheets',
    category: 'EXAMINATION',
  },
  {
    resource: 'REPORT_CARD',
    action: 'GENERATE',
    permissionString: 'report_card:generate',
    description: 'Compile grade report cards',
    category: 'EXAMINATION',
  },
  {
    resource: 'REPORT_CARD',
    action: 'PUBLISH',
    permissionString: 'report_card:publish',
    description: 'Release report cards to students/parents',
    category: 'EXAMINATION',
  },

  // Fees & Financial Ledger (10)
  {
    resource: 'FEE_STRUCTURE',
    action: 'CREATE',
    permissionString: 'fee_structure:create',
    description: 'Define class fee blueprints',
    category: 'FINANCE',
  },
  {
    resource: 'FEE_STRUCTURE',
    action: 'READ',
    permissionString: 'fee_structure:read',
    description: 'View fee structures and heads',
    category: 'FINANCE',
  },
  {
    resource: 'FEE_STRUCTURE',
    action: 'UPDATE',
    permissionString: 'fee_structure:update',
    description: 'Adjust fee structure rules',
    category: 'FINANCE',
  },
  {
    resource: 'FEE_STRUCTURE',
    action: 'DELETE',
    permissionString: 'fee_structure:delete',
    description: 'Delete fee structure',
    category: 'FINANCE',
  },
  {
    resource: 'FEE_INVOICE',
    action: 'CREATE',
    permissionString: 'fee_invoice:create',
    description: 'Generate fee invoices for students',
    category: 'FINANCE',
  },
  {
    resource: 'FEE_INVOICE',
    action: 'READ',
    permissionString: 'fee_invoice:read',
    description: 'View fee invoices and balances',
    category: 'FINANCE',
  },
  {
    resource: 'FEE_INVOICE',
    action: 'VOID',
    permissionString: 'fee_invoice:void',
    description: 'Cancel erroneous fee invoices',
    category: 'FINANCE',
  },
  {
    resource: 'PAYMENT',
    action: 'COLLECT',
    permissionString: 'payment:collect',
    description: 'Collect and record fee payments',
    category: 'FINANCE',
  },
  {
    resource: 'PAYMENT',
    action: 'READ',
    permissionString: 'payment:read',
    description: 'View receipt ledgers',
    category: 'FINANCE',
  },
  {
    resource: 'PAYMENT',
    action: 'REFUND',
    permissionString: 'payment:refund',
    description: 'Process fee refunds',
    category: 'FINANCE',
  },

  // HR & Payroll
  {
    resource: 'TEACHER',
    action: 'MANAGE',
    permissionString: 'teacher:manage',
    description: 'Manage teaching faculty profiles',
    category: 'HR',
  },
  {
    resource: 'STAFF',
    action: 'MANAGE',
    permissionString: 'staff:manage',
    description: 'Manage non-teaching staff profiles',
    category: 'HR',
  },
  {
    resource: 'EMPLOYEE',
    action: 'CREATE',
    permissionString: 'employee:create',
    description: 'Create new employee profile',
    category: 'HR',
  },
  {
    resource: 'EMPLOYEE',
    action: 'READ',
    permissionString: 'employee:read',
    description: 'View employee records',
    category: 'HR',
  },
  {
    resource: 'EMPLOYEE',
    action: 'UPDATE',
    permissionString: 'employee:update',
    description: 'Update employee profile details',
    category: 'HR',
  },
  {
    resource: 'EMPLOYEE',
    action: 'DELETE',
    permissionString: 'employee:delete',
    description: 'Archive or soft delete employee',
    category: 'HR',
  },
  {
    resource: 'EMPLOYEE',
    action: 'ACTIVATE',
    permissionString: 'employee:activate',
    description: 'Activate employee account',
    category: 'HR',
  },
  {
    resource: 'EMPLOYEE',
    action: 'DEACTIVATE',
    permissionString: 'employee:deactivate',
    description: 'Deactivate employee account',
    category: 'HR',
  },
  {
    resource: 'EMPLOYEE',
    action: 'SUSPEND',
    permissionString: 'employee:suspend',
    description: 'Suspend employee account',
    category: 'HR',
  },
  {
    resource: 'EMPLOYEE',
    action: 'TERMINATE',
    permissionString: 'employee:terminate',
    description: 'Terminate employee contract',
    category: 'HR',
  },
  {
    resource: 'EMPLOYEE',
    action: 'RESTORE',
    permissionString: 'employee:restore',
    description: 'Restore terminated or inactive employee',
    category: 'HR',
  },
  {
    resource: 'TEACHER',
    action: 'CREATE',
    permissionString: 'teacher:create',
    description: 'Create teacher academic profile',
    category: 'HR',
  },
  {
    resource: 'TEACHER',
    action: 'READ',
    permissionString: 'teacher:read',
    description: 'View teacher academic profiles',
    category: 'HR',
  },
  {
    resource: 'TEACHER',
    action: 'UPDATE',
    permissionString: 'teacher:update',
    description: 'Update teacher academic profile',
    category: 'HR',
  },
  {
    resource: 'TEACHER',
    action: 'DELETE',
    permissionString: 'teacher:delete',
    description: 'Archive teacher academic profile',
    category: 'HR',
  },
  {
    resource: 'DEPARTMENT',
    action: 'CREATE',
    permissionString: 'department:create',
    description: 'Create staff department',
    category: 'HR',
  },
  {
    resource: 'DEPARTMENT',
    action: 'READ',
    permissionString: 'department:read',
    description: 'View staff departments',
    category: 'HR',
  },
  {
    resource: 'DEPARTMENT',
    action: 'UPDATE',
    permissionString: 'department:update',
    description: 'Update staff department details',
    category: 'HR',
  },
  {
    resource: 'DEPARTMENT',
    action: 'DELETE',
    permissionString: 'department:delete',
    description: 'Archive staff department',
    category: 'HR',
  },
  {
    resource: 'DESIGNATION',
    action: 'CREATE',
    permissionString: 'designation:create',
    description: 'Create employee designation',
    category: 'HR',
  },
  {
    resource: 'DESIGNATION',
    action: 'READ',
    permissionString: 'designation:read',
    description: 'View employee designations',
    category: 'HR',
  },
  {
    resource: 'DESIGNATION',
    action: 'UPDATE',
    permissionString: 'designation:update',
    description: 'Update employee designation details',
    category: 'HR',
  },
  {
    resource: 'DESIGNATION',
    action: 'DELETE',
    permissionString: 'designation:delete',
    description: 'Archive employee designation',
    category: 'HR',
  },
  {
    resource: 'LEAVE',
    action: 'APPLY',
    permissionString: 'leave:apply',
    description: 'Submit employee leave request',
    category: 'HR',
  },
  {
    resource: 'LEAVE',
    action: 'APPROVE',
    permissionString: 'leave:approve',
    description: 'Approve or reject leave requests',
    category: 'HR',
  },
  {
    resource: 'PAYROLL',
    action: 'CALCULATE',
    permissionString: 'payroll:calculate',
    description: 'Compute monthly salary runs',
    category: 'HR',
  },
  {
    resource: 'PAYROLL',
    action: 'DISBURSE',
    permissionString: 'payroll:disburse',
    description: 'Finalize payroll and payouts',
    category: 'HR',
  },

  // Facilities & Operations (8)
  {
    resource: 'LIBRARY',
    action: 'CATALOG',
    permissionString: 'library:catalog',
    description: 'Manage library catalog and book copies',
    category: 'FACILITIES',
  },
  {
    resource: 'LIBRARY',
    action: 'CIRCULATION',
    permissionString: 'library:circulation',
    description: 'Issue, return, and fine library books',
    category: 'FACILITIES',
  },
  {
    resource: 'TRANSPORT',
    action: 'FLEET',
    permissionString: 'transport:fleet',
    description: 'Manage buses, vans, and drivers',
    category: 'FACILITIES',
  },
  {
    resource: 'TRANSPORT',
    action: 'ASSIGN',
    permissionString: 'transport:assign',
    description: 'Assign routes and stops to students',
    category: 'FACILITIES',
  },
  {
    resource: 'HOSTEL',
    action: 'MANAGE',
    permissionString: 'hostel:manage',
    description: 'Manage buildings, rooms, and beds',
    category: 'FACILITIES',
  },
  {
    resource: 'HOSTEL',
    action: 'ALLOCATE',
    permissionString: 'hostel:allocate',
    description: 'Allocate hostel rooms to students',
    category: 'FACILITIES',
  },
  {
    resource: 'INVENTORY',
    action: 'MANAGE',
    permissionString: 'inventory:manage',
    description: 'Manage inventory and stock balances',
    category: 'FACILITIES',
  },
  {
    resource: 'ANNOUNCEMENT',
    action: 'PUBLISH',
    permissionString: 'announcement:publish',
    description: 'Broadcast school-wide announcements',
    category: 'COMMUNICATION',
  },
];
