export interface PermissionSeedItem {
  resource: string;
  action: string;
  permissionString: string;
  description: string;
  category: string;
}

export const SYSTEM_PERMISSIONS: PermissionSeedItem[] = [
  // Tenant & System (5)
  {
    resource: 'TENANT',
    action: 'CREATE',
    permissionString: 'tenant:create',
    description: 'Create new tenant subscribers',
    category: 'SYSTEM',
  },
  {
    resource: 'TENANT',
    action: 'READ',
    permissionString: 'tenant:read',
    description: 'View tenant details',
    category: 'SYSTEM',
  },
  {
    resource: 'TENANT',
    action: 'UPDATE',
    permissionString: 'tenant:update',
    description: 'Update tenant config',
    category: 'SYSTEM',
  },
  {
    resource: 'TENANT',
    action: 'DELETE',
    permissionString: 'tenant:delete',
    description: 'Deactivate tenant',
    category: 'SYSTEM',
  },
  {
    resource: 'AUDIT',
    action: 'READ',
    permissionString: 'audit:read',
    description: 'Read system audit trail',
    category: 'SYSTEM',
  },

  // School & Campus Configuration
  {
    resource: 'SCHOOL',
    action: 'CREATE',
    permissionString: 'school:create',
    description: 'Create schools',
    category: 'ACADEMIC',
  },
  {
    resource: 'SCHOOL',
    action: 'READ',
    permissionString: 'school:read',
    description: 'View schools',
    category: 'ACADEMIC',
  },
  {
    resource: 'SCHOOL',
    action: 'UPDATE',
    permissionString: 'school:update',
    description: 'Update school details',
    category: 'ACADEMIC',
  },
  {
    resource: 'CAMPUS',
    action: 'CREATE',
    permissionString: 'campus:create',
    description: 'Create new campus sites',
    category: 'ACADEMIC',
  },
  {
    resource: 'CAMPUS',
    action: 'READ',
    permissionString: 'campus:read',
    description: 'View campus sites',
    category: 'ACADEMIC',
  },
  {
    resource: 'CAMPUS',
    action: 'UPDATE',
    permissionString: 'campus:update',
    description: 'Update campus details',
    category: 'ACADEMIC',
  },
  {
    resource: 'CAMPUS',
    action: 'DELETE',
    permissionString: 'campus:delete',
    description: 'Archive or deactivate campus sites',
    category: 'ACADEMIC',
  },
  {
    resource: 'CAMPUS',
    action: 'MANAGE',
    permissionString: 'campus:manage',
    description: 'Manage campus sites',
    category: 'ACADEMIC',
  },
  {
    resource: 'ACADEMIC_YEAR',
    action: 'CREATE',
    permissionString: 'academic_year:create',
    description: 'Create academic years',
    category: 'ACADEMIC',
  },
  {
    resource: 'ACADEMIC_YEAR',
    action: 'READ',
    permissionString: 'academic_year:read',
    description: 'View academic calendars',
    category: 'ACADEMIC',
  },
  {
    resource: 'ACADEMIC_YEAR',
    action: 'UPDATE',
    permissionString: 'academic_year:update',
    description: 'Update academic calendar details',
    category: 'ACADEMIC',
  },
  {
    resource: 'ACADEMIC_YEAR',
    action: 'ACTIVATE',
    permissionString: 'academic_year:activate',
    description: 'Activate academic year and set as current session',
    category: 'ACADEMIC',
  },
  {
    resource: 'ACADEMIC_YEAR',
    action: 'CLOSE',
    permissionString: 'academic_year:close',
    description: 'Close academic year session',
    category: 'ACADEMIC',
  },
  {
    resource: 'ACADEMIC_YEAR',
    action: 'MANAGE',
    permissionString: 'academic_year:manage',
    description: 'Manage academic calendars',
    category: 'ACADEMIC',
  },
  {
    resource: 'SETTINGS',
    action: 'READ',
    permissionString: 'settings:read',
    description: 'View school operational settings',
    category: 'ACADEMIC',
  },
  {
    resource: 'SETTINGS',
    action: 'UPDATE',
    permissionString: 'settings:update',
    description: 'Update school operational settings',
    category: 'ACADEMIC',
  },
  {
    resource: 'BRANDING',
    action: 'READ',
    permissionString: 'branding:read',
    description: 'View school branding assets',
    category: 'ACADEMIC',
  },
  {
    resource: 'BRANDING',
    action: 'UPDATE',
    permissionString: 'branding:update',
    description: 'Update school branding assets and display themes',
    category: 'ACADEMIC',
  },
  {
    resource: 'RBAC',
    action: 'MANAGE',
    permissionString: 'rbac:manage',
    description: 'Manage roles and permissions',
    category: 'SYSTEM',
  },

  // Academic Structure & Curriculum
  {
    resource: 'CLASS',
    action: 'CREATE',
    permissionString: 'class:create',
    description: 'Create new grades/classes',
    category: 'ACADEMIC',
  },
  {
    resource: 'CLASS',
    action: 'READ',
    permissionString: 'class:read',
    description: 'View grades and classes',
    category: 'ACADEMIC',
  },
  {
    resource: 'CLASS',
    action: 'UPDATE',
    permissionString: 'class:update',
    description: 'Update grade/class details',
    category: 'ACADEMIC',
  },
  {
    resource: 'CLASS',
    action: 'DELETE',
    permissionString: 'class:delete',
    description: 'Archive or delete grades/classes',
    category: 'ACADEMIC',
  },
  {
    resource: 'CLASS',
    action: 'MANAGE',
    permissionString: 'class:manage',
    description: 'Full management of grades/classes',
    category: 'ACADEMIC',
  },
  {
    resource: 'SECTION',
    action: 'CREATE',
    permissionString: 'section:create',
    description: 'Create new class sections',
    category: 'ACADEMIC',
  },
  {
    resource: 'SECTION',
    action: 'READ',
    permissionString: 'section:read',
    description: 'View class sections',
    category: 'ACADEMIC',
  },
  {
    resource: 'SECTION',
    action: 'UPDATE',
    permissionString: 'section:update',
    description: 'Update section configurations',
    category: 'ACADEMIC',
  },
  {
    resource: 'SECTION',
    action: 'DELETE',
    permissionString: 'section:delete',
    description: 'Delete or archive sections',
    category: 'ACADEMIC',
  },
  {
    resource: 'SECTION',
    action: 'MANAGE',
    permissionString: 'section:manage',
    description: 'Full management of class sections',
    category: 'ACADEMIC',
  },
  {
    resource: 'ACADEMIC_CLASS',
    action: 'CREATE',
    permissionString: 'academic_class:create',
    description: 'Create academic class offerings',
    category: 'ACADEMIC',
  },
  {
    resource: 'ACADEMIC_CLASS',
    action: 'READ',
    permissionString: 'academic_class:read',
    description: 'View academic class offerings',
    category: 'ACADEMIC',
  },
  {
    resource: 'ACADEMIC_CLASS',
    action: 'UPDATE',
    permissionString: 'academic_class:update',
    description: 'Update academic class offerings',
    category: 'ACADEMIC',
  },
  {
    resource: 'ACADEMIC_CLASS',
    action: 'DELETE',
    permissionString: 'academic_class:delete',
    description: 'Archive or delete academic classes',
    category: 'ACADEMIC',
  },
  {
    resource: 'ACADEMIC_CLASS',
    action: 'MANAGE',
    permissionString: 'academic_class:manage',
    description: 'Full management of academic classes',
    category: 'ACADEMIC',
  },
  {
    resource: 'SUBJECT',
    action: 'CREATE',
    permissionString: 'subject:create',
    description: 'Create curriculum subjects',
    category: 'ACADEMIC',
  },
  {
    resource: 'SUBJECT',
    action: 'READ',
    permissionString: 'subject:read',
    description: 'View curriculum subjects',
    category: 'ACADEMIC',
  },
  {
    resource: 'SUBJECT',
    action: 'UPDATE',
    permissionString: 'subject:update',
    description: 'Update curriculum subjects',
    category: 'ACADEMIC',
  },
  {
    resource: 'SUBJECT',
    action: 'DELETE',
    permissionString: 'subject:delete',
    description: 'Archive or remove subjects',
    category: 'ACADEMIC',
  },
  {
    resource: 'SUBJECT',
    action: 'MANAGE',
    permissionString: 'subject:manage',
    description: 'Full management of curriculum subjects',
    category: 'ACADEMIC',
  },
  {
    resource: 'CLASS_SUBJECT',
    action: 'CREATE',
    permissionString: 'class_subject:create',
    description: 'Map subjects to classes',
    category: 'ACADEMIC',
  },
  {
    resource: 'CLASS_SUBJECT',
    action: 'READ',
    permissionString: 'class_subject:read',
    description: 'View class subject mappings',
    category: 'ACADEMIC',
  },
  {
    resource: 'CLASS_SUBJECT',
    action: 'UPDATE',
    permissionString: 'class_subject:update',
    description: 'Update class subject mappings',
    category: 'ACADEMIC',
  },
  {
    resource: 'CLASS_SUBJECT',
    action: 'DELETE',
    permissionString: 'class_subject:delete',
    description: 'Remove class subject mappings',
    category: 'ACADEMIC',
  },
  {
    resource: 'CLASS_SUBJECT',
    action: 'MANAGE',
    permissionString: 'class_subject:manage',
    description: 'Full management of class subject mappings',
    category: 'ACADEMIC',
  },
  {
    resource: 'TEACHER_ASSIGNMENT',
    action: 'CREATE',
    permissionString: 'teacher_assignment:create',
    description: 'Assign teachers to subjects/sections',
    category: 'ACADEMIC',
  },
  {
    resource: 'TEACHER_ASSIGNMENT',
    action: 'READ',
    permissionString: 'teacher_assignment:read',
    description: 'View teacher subject assignments',
    category: 'ACADEMIC',
  },
  {
    resource: 'TEACHER_ASSIGNMENT',
    action: 'UPDATE',
    permissionString: 'teacher_assignment:update',
    description: 'Update teacher subject assignments',
    category: 'ACADEMIC',
  },
  {
    resource: 'TEACHER_ASSIGNMENT',
    action: 'DELETE',
    permissionString: 'teacher_assignment:delete',
    description: 'Remove teacher subject assignments',
    category: 'ACADEMIC',
  },
  {
    resource: 'TEACHER_ASSIGNMENT',
    action: 'MANAGE',
    permissionString: 'teacher_assignment:manage',
    description: 'Full management of teacher subject assignments',
    category: 'ACADEMIC',
  },
  {
    resource: 'ACADEMIC_ENROLLMENT',
    action: 'CREATE',
    permissionString: 'academic_enrollment:create',
    description: 'Enroll students into academic classes',
    category: 'ACADEMIC',
  },
  {
    resource: 'ACADEMIC_ENROLLMENT',
    action: 'READ',
    permissionString: 'academic_enrollment:read',
    description: 'View academic class enrollments',
    category: 'ACADEMIC',
  },
  {
    resource: 'ACADEMIC_ENROLLMENT',
    action: 'UPDATE',
    permissionString: 'academic_enrollment:update',
    description: 'Update enrollment and roll numbers',
    category: 'ACADEMIC',
  },
  {
    resource: 'ACADEMIC_ENROLLMENT',
    action: 'DELETE',
    permissionString: 'academic_enrollment:delete',
    description: 'Remove student academic enrollments',
    category: 'ACADEMIC',
  },
  {
    resource: 'ACADEMIC_ENROLLMENT',
    action: 'MANAGE',
    permissionString: 'academic_enrollment:manage',
    description: 'Full management of academic enrollments',
    category: 'ACADEMIC',
  },
  {
    resource: 'CLASS_TEACHER',
    action: 'ASSIGN',
    permissionString: 'class_teacher:assign',
    description: 'Assign class teachers to sections/academic classes',
    category: 'ACADEMIC',
  },
  {
    resource: 'TIMETABLE',
    action: 'CREATE',
    permissionString: 'timetable:create',
    description: 'Generate schedule timetable',
    category: 'ACADEMIC',
  },
  {
    resource: 'TIMETABLE',
    action: 'READ',
    permissionString: 'timetable:read',
    description: 'View schedule timetable',
    category: 'ACADEMIC',
  },
  {
    resource: 'TIMETABLE',
    action: 'UPDATE',
    permissionString: 'timetable:update',
    description: 'Modify schedule timetable',
    category: 'ACADEMIC',
  },
  {
    resource: 'TIMETABLE',
    action: 'PUBLISH',
    permissionString: 'timetable:publish',
    description: 'Publish timetable to students/teachers',
    category: 'ACADEMIC',
  },
  {
    resource: 'TIMETABLE',
    action: 'ARCHIVE',
    permissionString: 'timetable:archive',
    description: 'Archive active or historical timetable versions',
    category: 'ACADEMIC',
  },
  {
    resource: 'TIMETABLE',
    action: 'DELETE',
    permissionString: 'timetable:delete',
    description: 'Delete draft timetable versions',
    category: 'ACADEMIC',
  },
  {
    resource: 'TIMETABLE',
    action: 'MANAGE',
    permissionString: 'timetable:manage',
    description: 'Full management of timetables and scheduling',
    category: 'ACADEMIC',
  },
  {
    resource: 'TIMETABLE_ENTRY',
    action: 'CREATE',
    permissionString: 'timetable_entry:create',
    description: 'Schedule class slot entries',
    category: 'ACADEMIC',
  },
  {
    resource: 'TIMETABLE_ENTRY',
    action: 'READ',
    permissionString: 'timetable_entry:read',
    description: 'View scheduled timetable entries',
    category: 'ACADEMIC',
  },
  {
    resource: 'TIMETABLE_ENTRY',
    action: 'UPDATE',
    permissionString: 'timetable_entry:update',
    description: 'Modify scheduled timetable entries',
    category: 'ACADEMIC',
  },
  {
    resource: 'TIMETABLE_ENTRY',
    action: 'DELETE',
    permissionString: 'timetable_entry:delete',
    description: 'Remove scheduled timetable entries',
    category: 'ACADEMIC',
  },
  {
    resource: 'PERIOD',
    action: 'CREATE',
    permissionString: 'period:create',
    description: 'Create period and bell schedule configurations',
    category: 'ACADEMIC',
  },
  {
    resource: 'PERIOD',
    action: 'READ',
    permissionString: 'period:read',
    description: 'View periods and bell schedule configurations',
    category: 'ACADEMIC',
  },
  {
    resource: 'PERIOD',
    action: 'UPDATE',
    permissionString: 'period:update',
    description: 'Update periods and bell schedule configurations',
    category: 'ACADEMIC',
  },
  {
    resource: 'PERIOD',
    action: 'DELETE',
    permissionString: 'period:delete',
    description: 'Archive or remove periods',
    category: 'ACADEMIC',
  },
  {
    resource: 'PERIOD',
    action: 'MANAGE',
    permissionString: 'period:manage',
    description: 'Full management of period configurations',
    category: 'ACADEMIC',
  },
  {
    resource: 'ROOM',
    action: 'CREATE',
    permissionString: 'room:create',
    description: 'Create classrooms and physical facilities',
    category: 'ACADEMIC',
  },
  {
    resource: 'ROOM',
    action: 'READ',
    permissionString: 'room:read',
    description: 'View classrooms and room capacities',
    category: 'ACADEMIC',
  },
  {
    resource: 'ROOM',
    action: 'UPDATE',
    permissionString: 'room:update',
    description: 'Update classroom details and capacities',
    category: 'ACADEMIC',
  },
  {
    resource: 'ROOM',
    action: 'DELETE',
    permissionString: 'room:delete',
    description: 'Archive or remove classrooms',
    category: 'ACADEMIC',
  },
  {
    resource: 'ROOM',
    action: 'MANAGE',
    permissionString: 'room:manage',
    description: 'Full management of classrooms and facilities',
    category: 'ACADEMIC',
  },

  // Student & Admissions (11)
  {
    resource: 'STUDENT',
    action: 'CREATE',
    permissionString: 'student:create',
    description: 'Register new student profile',
    category: 'STUDENT',
  },
  {
    resource: 'STUDENT',
    action: 'READ',
    permissionString: 'student:read',
    description: 'View student profile and records',
    category: 'STUDENT',
  },
  {
    resource: 'STUDENT',
    action: 'UPDATE',
    permissionString: 'student:update',
    description: 'Modify student profile',
    category: 'STUDENT',
  },
  {
    resource: 'STUDENT',
    action: 'DELETE',
    permissionString: 'student:delete',
    description: 'Archive or soft delete student profile',
    category: 'STUDENT',
  },
  {
    resource: 'STUDENT',
    action: 'PROMOTE',
    permissionString: 'student:promote',
    description: 'Promote student to next academic grade',
    category: 'STUDENT',
  },
  {
    resource: 'STUDENT',
    action: 'TRANSFER',
    permissionString: 'student:transfer',
    description: 'Transfer or issue TC to student',
    category: 'STUDENT',
  },
  {
    resource: 'STUDENT',
    action: 'ADMIT',
    permissionString: 'student:admit',
    description: 'Admit student into the institution',
    category: 'STUDENT',
  },
  {
    resource: 'STUDENT',
    action: 'ACTIVATE',
    permissionString: 'student:activate',
    description: 'Activate student status',
    category: 'STUDENT',
  },
  {
    resource: 'STUDENT',
    action: 'SUSPEND',
    permissionString: 'student:suspend',
    description: 'Suspend student record',
    category: 'STUDENT',
  },
  {
    resource: 'STUDENT',
    action: 'WITHDRAW',
    permissionString: 'student:withdraw',
    description: 'Process student withdrawal',
    category: 'STUDENT',
  },
  {
    resource: 'STUDENT',
    action: 'GRADUATE',
    permissionString: 'student:graduate',
    description: 'Graduate student record',
    category: 'STUDENT',
  },
  {
    resource: 'STUDENT',
    action: 'ARCHIVE',
    permissionString: 'student:archive',
    description: 'Archive student historical record',
    category: 'STUDENT',
  },

  // Guardian Management (4)
  {
    resource: 'GUARDIAN',
    action: 'CREATE',
    permissionString: 'guardian:create',
    description: 'Create parent/guardian record',
    category: 'STUDENT',
  },
  {
    resource: 'GUARDIAN',
    action: 'READ',
    permissionString: 'guardian:read',
    description: 'View parent/guardian record',
    category: 'STUDENT',
  },
  {
    resource: 'GUARDIAN',
    action: 'UPDATE',
    permissionString: 'guardian:update',
    description: 'Update parent/guardian record',
    category: 'STUDENT',
  },
  {
    resource: 'GUARDIAN',
    action: 'DELETE',
    permissionString: 'guardian:delete',
    description: 'Remove or archive parent/guardian record',
    category: 'STUDENT',
  },

  // Student-Guardian Relationships (4)
  {
    resource: 'RELATIONSHIP',
    action: 'CREATE',
    permissionString: 'relationship:create',
    description: 'Link guardian to student',
    category: 'STUDENT',
  },
  {
    resource: 'RELATIONSHIP',
    action: 'READ',
    permissionString: 'relationship:read',
    description: 'View student-guardian relationships',
    category: 'STUDENT',
  },
  {
    resource: 'RELATIONSHIP',
    action: 'UPDATE',
    permissionString: 'relationship:update',
    description: 'Update student-guardian relationship flags and permissions',
    category: 'STUDENT',
  },
  {
    resource: 'RELATIONSHIP',
    action: 'DELETE',
    permissionString: 'relationship:delete',
    description: 'Unlink guardian from student',
    category: 'STUDENT',
  },

  // Student Enrollment (4)
  {
    resource: 'ENROLLMENT',
    action: 'CREATE',
    permissionString: 'enrollment:create',
    description: 'Enroll student into academic session',
    category: 'ACADEMIC',
  },
  {
    resource: 'ENROLLMENT',
    action: 'READ',
    permissionString: 'enrollment:read',
    description: 'View student enrollment history',
    category: 'ACADEMIC',
  },
  {
    resource: 'ENROLLMENT',
    action: 'UPDATE',
    permissionString: 'enrollment:update',
    description: 'Update enrollment record details',
    category: 'ACADEMIC',
  },
  {
    resource: 'ENROLLMENT',
    action: 'TRANSFER',
    permissionString: 'enrollment:transfer',
    description: 'Transfer enrollment between campuses or sessions',
    category: 'ACADEMIC',
  },

  // Student Documents (5)
  {
    resource: 'STUDENT_DOCUMENT',
    action: 'CREATE',
    permissionString: 'student_document:create',
    description: 'Upload student compliance and identity documents',
    category: 'STUDENT',
  },
  {
    resource: 'STUDENT_DOCUMENT',
    action: 'READ',
    permissionString: 'student_document:read',
    description: 'View student documents',
    category: 'STUDENT',
  },
  {
    resource: 'STUDENT_DOCUMENT',
    action: 'UPDATE',
    permissionString: 'student_document:update',
    description: 'Update student document metadata',
    category: 'STUDENT',
  },
  {
    resource: 'STUDENT_DOCUMENT',
    action: 'VERIFY',
    permissionString: 'student_document:verify',
    description: 'Verify or reject student documents',
    category: 'STUDENT',
  },
  {
    resource: 'STUDENT_DOCUMENT',
    action: 'DELETE',
    permissionString: 'student_document:delete',
    description: 'Delete student document',
    category: 'STUDENT',
  },
  {
    resource: 'ADMISSION',
    action: 'CREATE',
    permissionString: 'admission:create',
    description: 'Submit admission application',
    category: 'ADMISSION',
  },
  {
    resource: 'ADMISSION',
    action: 'READ',
    permissionString: 'admission:read',
    description: 'View admission applications',
    category: 'ADMISSION',
  },
  {
    resource: 'ADMISSION',
    action: 'REVIEW',
    permissionString: 'admission:review',
    description: 'Review and verify applicant documents',
    category: 'ADMISSION',
  },
  {
    resource: 'ADMISSION',
    action: 'APPROVE',
    permissionString: 'admission:approve',
    description: 'Grant official admission approval',
    category: 'ADMISSION',
  },
  {
    resource: 'ADMISSION',
    action: 'REJECT',
    permissionString: 'admission:reject',
    description: 'Reject admission application',
    category: 'ADMISSION',
  },

  // Attendance & Classroom
  {
    resource: 'ATTENDANCE',
    action: 'CREATE',
    permissionString: 'attendance:create',
    description: 'Create or draft student attendance',
    category: 'ATTENDANCE',
  },
  {
    resource: 'ATTENDANCE',
    action: 'MARK',
    permissionString: 'attendance:mark',
    description: 'Submit daily attendance for students',
    category: 'ATTENDANCE',
  },
  {
    resource: 'ATTENDANCE',
    action: 'READ',
    permissionString: 'attendance:read',
    description: 'View student attendance records',
    category: 'ATTENDANCE',
  },
  {
    resource: 'ATTENDANCE',
    action: 'UPDATE',
    permissionString: 'attendance:update',
    description: 'Correct previously submitted attendance',
    category: 'ATTENDANCE',
  },
  {
    resource: 'ATTENDANCE',
    action: 'SUBMIT',
    permissionString: 'attendance:submit',
    description: 'Submit class attendance for review/finalization',
    category: 'ATTENDANCE',
  },
  {
    resource: 'ATTENDANCE',
    action: 'APPROVE',
    permissionString: 'attendance:approve',
    description: 'Approve submitted class attendance',
    category: 'ATTENDANCE',
  },
  {
    resource: 'ATTENDANCE',
    action: 'LOCK',
    permissionString: 'attendance:lock',
    description: 'Lock attendance registers against editing',
    category: 'ATTENDANCE',
  },
  {
    resource: 'ATTENDANCE',
    action: 'CORRECT',
    permissionString: 'attendance:correct',
    description: 'Request or execute attendance corrections',
    category: 'ATTENDANCE',
  },
  {
    resource: 'ATTENDANCE',
    action: 'REPORT',
    permissionString: 'attendance:report',
    description: 'View attendance analytics and summaries',
    category: 'ATTENDANCE',
  },
  {
    resource: 'ATTENDANCE',
    action: 'EXPORT',
    permissionString: 'attendance:export',
    description: 'Download attendance reports',
    category: 'ATTENDANCE',
  },
  {
    resource: 'HOLIDAY',
    action: 'CREATE',
    permissionString: 'holiday:create',
    description: 'Declare school holidays and calendar breaks',
    category: 'ATTENDANCE',
  },
  {
    resource: 'HOLIDAY',
    action: 'READ',
    permissionString: 'holiday:read',
    description: 'View declared school holidays',
    category: 'ATTENDANCE',
  },
  {
    resource: 'HOLIDAY',
    action: 'UPDATE',
    permissionString: 'holiday:update',
    description: 'Modify declared school holidays',
    category: 'ATTENDANCE',
  },
  {
    resource: 'HOLIDAY',
    action: 'DELETE',
    permissionString: 'holiday:delete',
    description: 'Remove declared school holidays',
    category: 'ATTENDANCE',
  },
  {
    resource: 'STAFF_ATTENDANCE',
    action: 'MARK',
    permissionString: 'staff_attendance:mark',
    description: 'Record employee attendance',
    category: 'HR',
  },
  {
    resource: 'STAFF_ATTENDANCE',
    action: 'READ',
    permissionString: 'staff_attendance:read',
    description: 'View employee attendance logs',
    category: 'HR',
  },

  // Homework & Assignments (5)
  {
    resource: 'HOMEWORK',
    action: 'CREATE',
    permissionString: 'homework:create',
    description: 'Publish homework assignments',
    category: 'ACADEMIC',
  },
  {
    resource: 'HOMEWORK',
    action: 'READ',
    permissionString: 'homework:read',
    description: 'View assigned homework',
    category: 'ACADEMIC',
  },
  {
    resource: 'HOMEWORK',
    action: 'UPDATE',
    permissionString: 'homework:update',
    description: 'Edit homework details and due date',
    category: 'ACADEMIC',
  },
  {
    resource: 'HOMEWORK',
    action: 'GRADE',
    permissionString: 'homework:grade',
    description: 'Grade and provide feedback on submissions',
    category: 'ACADEMIC',
  },
  {
    resource: 'HOMEWORK',
    action: 'SUBMIT',
    permissionString: 'homework:submit',
    description: 'Upload completed homework solution',
    category: 'ACADEMIC',
  },

  // Examinations & Grading (9)
  {
    resource: 'EXAM',
    action: 'CREATE',
    permissionString: 'exam:create',
    description: 'Configure examination cycles',
    category: 'EXAMINATION',
  },
  {
    resource: 'EXAM',
    action: 'READ',
    permissionString: 'exam:read',
    description: 'View exam details',
    category: 'EXAMINATION',
  },
  {
    resource: 'EXAM',
    action: 'SCHEDULE',
    permissionString: 'exam:schedule',
    description: 'Schedule exam timetable and rooms',
    category: 'EXAMINATION',
  },
  {
    resource: 'EXAM',
    action: 'PUBLISH',
    permissionString: 'exam:publish',
    description: 'Publish examination timetables',
    category: 'EXAMINATION',
  },
  {
    resource: 'EXAM',
    action: 'LOCK',
    permissionString: 'exam:lock',
    description: 'Lock completed examination entries',
    category: 'EXAMINATION',
  },
  {
    resource: 'MARKS',
    action: 'ENTRY',
    permissionString: 'marks:entry',
    description: 'Input student marks for subject',
    category: 'EXAMINATION',
  },
  {
    resource: 'MARKS',
    action: 'VERIFY',
    permissionString: 'marks:verify',
    description: 'Verify and approve grade sheets',
    category: 'EXAMINATION',
  },
  {
    resource: 'REPORT_CARD',
    action: 'GENERATE',
    permissionString: 'report_card:generate',
    description: 'Compile grade report cards',
    category: 'EXAMINATION',
  },
  {
    resource: 'REPORT_CARD',
    action: 'PUBLISH',
    permissionString: 'report_card:publish',
    description: 'Release report cards to students/parents',
    category: 'EXAMINATION',
  },

  // Fees & Financial Ledger (10)
  {
    resource: 'FEE_STRUCTURE',
    action: 'CREATE',
    permissionString: 'fee_structure:create',
    description: 'Define class fee blueprints',
    category: 'FINANCE',
  },
  {
    resource: 'FEE_STRUCTURE',
    action: 'READ',
    permissionString: 'fee_structure:read',
    description: 'View fee structures and heads',
    category: 'FINANCE',
  },
  {
    resource: 'FEE_STRUCTURE',
    action: 'UPDATE',
    permissionString: 'fee_structure:update',
    description: 'Adjust fee structure rules',
    category: 'FINANCE',
  },
  {
    resource: 'FEE_STRUCTURE',
    action: 'DELETE',
    permissionString: 'fee_structure:delete',
    description: 'Delete fee structure',
    category: 'FINANCE',
  },
  {
    resource: 'FEE_INVOICE',
    action: 'CREATE',
    permissionString: 'fee_invoice:create',
    description: 'Generate fee invoices for students',
    category: 'FINANCE',
  },
  {
    resource: 'FEE_INVOICE',
    action: 'READ',
    permissionString: 'fee_invoice:read',
    description: 'View fee invoices and balances',
    category: 'FINANCE',
  },
  {
    resource: 'FEE_INVOICE',
    action: 'VOID',
    permissionString: 'fee_invoice:void',
    description: 'Cancel erroneous fee invoices',
    category: 'FINANCE',
  },
  {
    resource: 'PAYMENT',
    action: 'COLLECT',
    permissionString: 'payment:collect',
    description: 'Collect and record fee payments',
    category: 'FINANCE',
  },
  {
    resource: 'PAYMENT',
    action: 'READ',
    permissionString: 'payment:read',
    description: 'View receipt ledgers',
    category: 'FINANCE',
  },
  {
    resource: 'PAYMENT',
    action: 'REFUND',
    permissionString: 'payment:refund',
    description: 'Process fee refunds',
    category: 'FINANCE',
  },

  // HR & Payroll
  {
    resource: 'TEACHER',
    action: 'MANAGE',
    permissionString: 'teacher:manage',
    description: 'Manage teaching faculty profiles',
    category: 'HR',
  },
  {
    resource: 'STAFF',
    action: 'MANAGE',
    permissionString: 'staff:manage',
    description: 'Manage non-teaching staff profiles',
    category: 'HR',
  },
  {
    resource: 'EMPLOYEE',
    action: 'CREATE',
    permissionString: 'employee:create',
    description: 'Create new employee profile',
    category: 'HR',
  },
  {
    resource: 'EMPLOYEE',
    action: 'READ',
    permissionString: 'employee:read',
    description: 'View employee records',
    category: 'HR',
  },
  {
    resource: 'EMPLOYEE',
    action: 'UPDATE',
    permissionString: 'employee:update',
    description: 'Update employee profile details',
    category: 'HR',
  },
  {
    resource: 'EMPLOYEE',
    action: 'DELETE',
    permissionString: 'employee:delete',
    description: 'Archive or soft delete employee',
    category: 'HR',
  },
  {
    resource: 'EMPLOYEE',
    action: 'ACTIVATE',
    permissionString: 'employee:activate',
    description: 'Activate employee account',
    category: 'HR',
  },
  {
    resource: 'EMPLOYEE',
    action: 'DEACTIVATE',
    permissionString: 'employee:deactivate',
    description: 'Deactivate employee account',
    category: 'HR',
  },
  {
    resource: 'EMPLOYEE',
    action: 'SUSPEND',
    permissionString: 'employee:suspend',
    description: 'Suspend employee account',
    category: 'HR',
  },
  {
    resource: 'EMPLOYEE',
    action: 'TERMINATE',
    permissionString: 'employee:terminate',
    description: 'Terminate employee contract',
    category: 'HR',
  },
  {
    resource: 'EMPLOYEE',
    action: 'RESTORE',
    permissionString: 'employee:restore',
    description: 'Restore terminated or inactive employee',
    category: 'HR',
  },
  {
    resource: 'TEACHER',
    action: 'CREATE',
    permissionString: 'teacher:create',
    description: 'Create teacher academic profile',
    category: 'HR',
  },
  {
    resource: 'TEACHER',
    action: 'READ',
    permissionString: 'teacher:read',
    description: 'View teacher academic profiles',
    category: 'HR',
  },
  {
    resource: 'TEACHER',
    action: 'UPDATE',
    permissionString: 'teacher:update',
    description: 'Update teacher academic profile',
    category: 'HR',
  },
  {
    resource: 'TEACHER',
    action: 'DELETE',
    permissionString: 'teacher:delete',
    description: 'Archive teacher academic profile',
    category: 'HR',
  },
  {
    resource: 'DEPARTMENT',
    action: 'CREATE',
    permissionString: 'department:create',
    description: 'Create staff department',
    category: 'HR',
  },
  {
    resource: 'DEPARTMENT',
    action: 'READ',
    permissionString: 'department:read',
    description: 'View staff departments',
    category: 'HR',
  },
  {
    resource: 'DEPARTMENT',
    action: 'UPDATE',
    permissionString: 'department:update',
    description: 'Update staff department details',
    category: 'HR',
  },
  {
    resource: 'DEPARTMENT',
    action: 'DELETE',
    permissionString: 'department:delete',
    description: 'Archive staff department',
    category: 'HR',
  },
  {
    resource: 'DESIGNATION',
    action: 'CREATE',
    permissionString: 'designation:create',
    description: 'Create employee designation',
    category: 'HR',
  },
  {
    resource: 'DESIGNATION',
    action: 'READ',
    permissionString: 'designation:read',
    description: 'View employee designations',
    category: 'HR',
  },
  {
    resource: 'DESIGNATION',
    action: 'UPDATE',
    permissionString: 'designation:update',
    description: 'Update employee designation details',
    category: 'HR',
  },
  {
    resource: 'DESIGNATION',
    action: 'DELETE',
    permissionString: 'designation:delete',
    description: 'Archive employee designation',
    category: 'HR',
  },
  {
    resource: 'LEAVE',
    action: 'APPLY',
    permissionString: 'leave:apply',
    description: 'Submit employee leave request',
    category: 'HR',
  },
  {
    resource: 'LEAVE',
    action: 'APPROVE',
    permissionString: 'leave:approve',
    description: 'Approve or reject leave requests',
    category: 'HR',
  },
  {
    resource: 'PAYROLL',
    action: 'CALCULATE',
    permissionString: 'payroll:calculate',
    description: 'Compute monthly salary runs',
    category: 'HR',
  },
  {
    resource: 'PAYROLL',
    action: 'DISBURSE',
    permissionString: 'payroll:disburse',
    description: 'Finalize payroll and payouts',
    category: 'HR',
  },

  // Facilities & Operations (8)
  {
    resource: 'LIBRARY',
    action: 'CATALOG',
    permissionString: 'library:catalog',
    description: 'Manage library catalog and book copies',
    category: 'FACILITIES',
  },
  {
    resource: 'LIBRARY',
    action: 'CIRCULATION',
    permissionString: 'library:circulation',
    description: 'Issue, return, and fine library books',
    category: 'FACILITIES',
  },
  {
    resource: 'TRANSPORT',
    action: 'FLEET',
    permissionString: 'transport:fleet',
    description: 'Manage buses, vans, and drivers',
    category: 'FACILITIES',
  },
  {
    resource: 'TRANSPORT',
    action: 'ASSIGN',
    permissionString: 'transport:assign',
    description: 'Assign routes and stops to students',
    category: 'FACILITIES',
  },
  {
    resource: 'HOSTEL',
    action: 'MANAGE',
    permissionString: 'hostel:manage',
    description: 'Manage buildings, rooms, and beds',
    category: 'FACILITIES',
  },
  {
    resource: 'HOSTEL',
    action: 'ALLOCATE',
    permissionString: 'hostel:allocate',
    description: 'Allocate hostel rooms to students',
    category: 'FACILITIES',
  },
  {
    resource: 'INVENTORY',
    action: 'MANAGE',
    permissionString: 'inventory:manage',
    description: 'Manage inventory and stock balances',
    category: 'FACILITIES',
  },
  {
    resource: 'ANNOUNCEMENT',
    action: 'PUBLISH',
    permissionString: 'announcement:publish',
    description: 'Broadcast school-wide announcements',
    category: 'COMMUNICATION',
  },
];
