import { UserType } from '@edusphere/common';

export interface SystemRoleDefinition {
  name: string;
  userType: UserType;
  description: string;
  permissions: string[]; // permissionString array
}

export const SYSTEM_ROLES: SystemRoleDefinition[] = [
  {
    name: 'SUPER_ADMIN',
    userType: UserType.SUPER_ADMIN,
    description: 'SaaS Platform Super Administrator with unrestricted access',
    permissions: ['*'], // Grants all permissions
  },
  {
    name: 'SCHOOL_ADMIN',
    userType: UserType.SCHOOL_ADMIN,
    description: 'Institutional Administrator managing entire school operations',
    permissions: [
      'tenant:read',
      'tenant:update',
      'school:read',
      'school:update',
      'campus:create',
      'campus:read',
      'campus:update',
      'campus:delete',
      'campus:manage',
      'academic_year:create',
      'academic_year:read',
      'academic_year:update',
      'academic_year:activate',
      'academic_year:close',
      'academic_year:manage',
      'settings:read',
      'settings:update',
      'branding:read',
      'branding:update',
      'rbac:manage',
      'class:manage',
      'section:manage',
      'subject:manage',
      'teacher_assignment:manage',
      'timetable:create',
      'timetable:read',
      'timetable:update',
      'timetable:publish',
      'student:create',
      'student:read',
      'student:update',
      'student:delete',
      'student:promote',
      'student:transfer',
      'admission:create',
      'admission:read',
      'admission:review',
      'admission:approve',
      'admission:reject',
      'attendance:mark',
      'attendance:read',
      'attendance:update',
      'attendance:lock',
      'attendance:export',
      'staff_attendance:mark',
      'staff_attendance:read',
      'homework:create',
      'homework:read',
      'homework:update',
      'homework:grade',
      'exam:create',
      'exam:read',
      'exam:schedule',
      'exam:publish',
      'exam:lock',
      'marks:entry',
      'marks:verify',
      'report_card:generate',
      'report_card:publish',
      'fee_structure:create',
      'fee_structure:read',
      'fee_structure:update',
      'fee_structure:delete',
      'fee_invoice:create',
      'fee_invoice:read',
      'fee_invoice:void',
      'payment:collect',
      'payment:read',
      'payment:refund',
      'teacher:manage',
      'staff:manage',
      'leave:apply',
      'leave:approve',
      'payroll:calculate',
      'payroll:disburse',
      'library:catalog',
      'library:circulation',
      'transport:fleet',
      'transport:assign',
      'hostel:manage',
      'hostel:allocate',
      'inventory:manage',
      'announcement:publish',
      'audit:read',
    ],
  },
  {
    name: 'PRINCIPAL',
    userType: UserType.PRINCIPAL,
    description: 'Head of Institution overseeing academic and operational policies',
    permissions: [
      'school:read',
      'class:manage',
      'section:manage',
      'subject:manage',
      'timetable:read',
      'timetable:publish',
      'student:read',
      'student:promote',
      'student:transfer',
      'admission:read',
      'admission:review',
      'admission:approve',
      'attendance:read',
      'attendance:lock',
      'attendance:export',
      'exam:read',
      'exam:publish',
      'marks:verify',
      'report_card:generate',
      'report_card:publish',
      'fee_structure:read',
      'fee_invoice:read',
      'payment:read',
      'teacher:manage',
      'staff:manage',
      'leave:approve',
      'announcement:publish',
      'audit:read',
    ],
  },
  {
    name: 'VICE_PRINCIPAL',
    userType: UserType.VICE_PRINCIPAL,
    description: 'Deputy Academic Head supervising daily curriculum and attendance',
    permissions: [
      'school:read',
      'class:manage',
      'section:manage',
      'subject:manage',
      'timetable:read',
      'student:read',
      'attendance:read',
      'attendance:update',
      'attendance:export',
      'exam:read',
      'marks:entry',
      'marks:verify',
      'report_card:generate',
      'leave:approve',
      'announcement:publish',
    ],
  },
  {
    name: 'TEACHER',
    userType: UserType.TEACHER,
    description: 'Faculty member managing classroom, daily attendance, homework, and marks',
    permissions: [
      'student:read',
      'attendance:mark',
      'attendance:read',
      'homework:create',
      'homework:read',
      'homework:update',
      'homework:grade',
      'marks:entry',
      'leave:apply',
      'announcement:publish',
    ],
  },
  {
    name: 'ACCOUNTANT',
    userType: UserType.ACCOUNTANT,
    description: 'Finance Officer managing fee structures, invoicing, collections, and refunds',
    permissions: [
      'student:read',
      'fee_structure:create',
      'fee_structure:read',
      'fee_structure:update',
      'fee_invoice:create',
      'fee_invoice:read',
      'fee_invoice:void',
      'payment:collect',
      'payment:read',
      'payment:refund',
      'leave:apply',
    ],
  },
  {
    name: 'HR_MANAGER',
    userType: UserType.HR_MANAGER,
    description: 'Human Resources Officer handling employee records, leave, and payroll',
    permissions: [
      'teacher:manage',
      'staff:manage',
      'staff_attendance:mark',
      'staff_attendance:read',
      'leave:apply',
      'leave:approve',
      'payroll:calculate',
      'payroll:disburse',
    ],
  },
  {
    name: 'LIBRARIAN',
    userType: UserType.LIBRARIAN,
    description: 'Library custodian overseeing cataloging, loans, and returns',
    permissions: ['student:read', 'library:catalog', 'library:circulation', 'leave:apply'],
  },
  {
    name: 'TRANSPORT_MANAGER',
    userType: UserType.TRANSPORT_MANAGER,
    description: 'Logistics coordinator managing buses, routes, and stops',
    permissions: ['student:read', 'transport:fleet', 'transport:assign', 'leave:apply'],
  },
  {
    name: 'HOSTEL_MANAGER',
    userType: UserType.HOSTEL_MANAGER,
    description: 'Hostel warden managing buildings, rooms, and student bed allocations',
    permissions: ['student:read', 'hostel:manage', 'hostel:allocate', 'leave:apply'],
  },
  {
    name: 'RECEPTIONIST',
    userType: UserType.RECEPTIONIST,
    description: 'Front desk coordinator managing visitor inquiries and admissions',
    permissions: ['student:read', 'admission:create', 'admission:read', 'leave:apply'],
  },
  {
    name: 'STAFF',
    userType: UserType.STAFF,
    description: 'General support employee with basic self-service portal access',
    permissions: ['leave:apply'],
  },
  {
    name: 'STUDENT',
    userType: UserType.STUDENT,
    description: 'Enrolled learner accessing timetables, attendance, homework, and reports',
    permissions: [
      'student:read',
      'attendance:read',
      'homework:read',
      'homework:submit',
      'fee_invoice:read',
    ],
  },
  {
    name: 'PARENT',
    userType: UserType.PARENT,
    description: 'Guardian tracking student progress, fee payments, and announcements',
    permissions: ['student:read', 'attendance:read', 'homework:read', 'fee_invoice:read'],
  },
];
