import { UserType } from '@edusphere/common';

export interface SystemRoleDefinition {
  name: string;
  userType: UserType;
  description: string;
  permissions: string[]; // permissionString array
}

export const SYSTEM_ROLES: SystemRoleDefinition[] = [
  {
    name: 'SUPER_ADMIN',
    userType: UserType.SUPER_ADMIN,
    description: 'SaaS Platform Super Administrator with unrestricted access',
    permissions: ['*'], // Grants all permissions
  },
  {
    name: 'SCHOOL_ADMIN',
    userType: UserType.SCHOOL_ADMIN,
    description: 'Institutional Administrator managing entire school operations',
    permissions: [
      'tenant:read',
      'tenant:update',
      'school:read',
      'school:update',
      'campus:create',
      'campus:read',
      'campus:update',
      'campus:delete',
      'campus:manage',
      'academic_year:create',
      'academic_year:read',
      'academic_year:update',
      'academic_year:activate',
      'academic_year:close',
      'academic_year:manage',
      'settings:read',
      'settings:update',
      'branding:read',
      'branding:update',
      'rbac:manage',
      'class:create',
      'class:read',
      'class:update',
      'class:delete',
      'class:manage',
      'section:create',
      'section:read',
      'section:update',
      'section:delete',
      'section:manage',
      'academic_class:create',
      'academic_class:read',
      'academic_class:update',
      'academic_class:delete',
      'academic_class:manage',
      'subject:create',
      'subject:read',
      'subject:update',
      'subject:delete',
      'subject:manage',
      'class_subject:create',
      'class_subject:read',
      'class_subject:update',
      'class_subject:delete',
      'class_subject:manage',
      'teacher_assignment:create',
      'teacher_assignment:read',
      'teacher_assignment:update',
      'teacher_assignment:delete',
      'teacher_assignment:manage',
      'academic_enrollment:create',
      'academic_enrollment:read',
      'academic_enrollment:update',
      'academic_enrollment:delete',
      'academic_enrollment:manage',
      'class_teacher:assign',
      'timetable:create',
      'timetable:read',
      'timetable:update',
      'timetable:publish',
      'timetable:archive',
      'timetable:delete',
      'timetable:manage',
      'timetable_entry:create',
      'timetable_entry:read',
      'timetable_entry:update',
      'timetable_entry:delete',
      'period:create',
      'period:read',
      'period:update',
      'period:delete',
      'period:manage',
      'room:create',
      'room:read',
      'room:update',
      'room:delete',
      'room:manage',
      'student:create',
      'student:read',
      'student:update',
      'student:delete',
      'student:promote',
      'student:transfer',
      'student:admit',
      'student:activate',
      'student:suspend',
      'student:withdraw',
      'student:graduate',
      'student:archive',
      'guardian:create',
      'guardian:read',
      'guardian:update',
      'guardian:delete',
      'relationship:create',
      'relationship:read',
      'relationship:update',
      'relationship:delete',
      'enrollment:create',
      'enrollment:read',
      'enrollment:update',
      'enrollment:transfer',
      'student_document:create',
      'student_document:read',
      'student_document:update',
      'student_document:verify',
      'student_document:delete',
      'admission:create',
      'admission:read',
      'admission:review',
      'admission:approve',
      'admission:reject',
      'attendance:create',
      'attendance:mark',
      'attendance:read',
      'attendance:update',
      'attendance:submit',
      'attendance:approve',
      'attendance:lock',
      'attendance:correct',
      'attendance:report',
      'attendance:export',
      'holiday:create',
      'holiday:read',
      'holiday:update',
      'holiday:delete',
      'staff_attendance:mark',
      'staff_attendance:read',
      'homework:create',
      'homework:read',
      'homework:update',
      'homework:grade',
      'exam:create',
      'exam:read',
      'exam:schedule',
      'exam:publish',
      'exam:lock',
      'marks:entry',
      'marks:verify',
      'report_card:generate',
      'report_card:publish',
      'fee_structure:create',
      'fee_structure:read',
      'fee_structure:update',
      'fee_structure:delete',
      'fee_invoice:create',
      'fee_invoice:read',
      'fee_invoice:void',
      'payment:collect',
      'payment:read',
      'payment:refund',
      'teacher:manage',
      'staff:manage',
      'employee:create',
      'employee:read',
      'employee:update',
      'employee:delete',
      'employee:activate',
      'employee:deactivate',
      'employee:suspend',
      'employee:terminate',
      'employee:restore',
      'teacher:create',
      'teacher:read',
      'teacher:update',
      'teacher:delete',
      'department:create',
      'department:read',
      'department:update',
      'department:delete',
      'designation:create',
      'designation:read',
      'designation:update',
      'designation:delete',
      'leave:apply',
      'leave:approve',
      'payroll:calculate',
      'payroll:disburse',
      'library:catalog',
      'library:circulation',
      'transport:fleet',
      'transport:assign',
      'hostel:manage',
      'hostel:allocate',
      'inventory:manage',
      'announcement:publish',
      'audit:read',
    ],
  },
  {
    name: 'PRINCIPAL',
    userType: UserType.PRINCIPAL,
    description: 'Head of Institution overseeing academic and operational policies',
    permissions: [
      'school:read',
      'class:create',
      'class:read',
      'class:update',
      'class:delete',
      'class:manage',
      'section:create',
      'section:read',
      'section:update',
      'section:delete',
      'section:manage',
      'academic_class:create',
      'academic_class:read',
      'academic_class:update',
      'academic_class:delete',
      'academic_class:manage',
      'subject:create',
      'subject:read',
      'subject:update',
      'subject:delete',
      'subject:manage',
      'class_subject:create',
      'class_subject:read',
      'class_subject:update',
      'class_subject:delete',
      'class_subject:manage',
      'teacher_assignment:create',
      'teacher_assignment:read',
      'teacher_assignment:update',
      'teacher_assignment:delete',
      'teacher_assignment:manage',
      'academic_enrollment:create',
      'academic_enrollment:read',
      'academic_enrollment:update',
      'academic_enrollment:delete',
      'academic_enrollment:manage',
      'class_teacher:assign',
      'timetable:read',
      'timetable:publish',
      'timetable:archive',
      'timetable_entry:create',
      'timetable_entry:read',
      'timetable_entry:update',
      'timetable_entry:delete',
      'period:create',
      'period:read',
      'period:update',
      'room:create',
      'room:read',
      'room:update',
      'student:read',
      'student:promote',
      'student:transfer',
      'student:admit',
      'student:activate',
      'student:suspend',
      'student:withdraw',
      'student:graduate',
      'guardian:read',
      'relationship:read',
      'enrollment:read',
      'student_document:read',
      'student_document:verify',
      'admission:read',
      'admission:review',
      'admission:approve',
      'attendance:create',
      'attendance:mark',
      'attendance:read',
      'attendance:update',
      'attendance:submit',
      'attendance:approve',
      'attendance:lock',
      'attendance:correct',
      'attendance:report',
      'attendance:export',
      'holiday:create',
      'holiday:read',
      'holiday:update',
      'holiday:delete',
      'exam:read',
      'exam:publish',
      'marks:verify',
      'report_card:generate',
      'report_card:publish',
      'fee_structure:read',
      'fee_invoice:read',
      'payment:read',
      'teacher:manage',
      'staff:manage',
      'employee:read',
      'employee:update',
      'teacher:read',
      'teacher:update',
      'department:read',
      'designation:read',
      'leave:approve',
      'announcement:publish',
      'audit:read',
    ],
  },
  {
    name: 'VICE_PRINCIPAL',
    userType: UserType.VICE_PRINCIPAL,
    description: 'Deputy Academic Head supervising daily curriculum and attendance',
    permissions: [
      'school:read',
      'class:create',
      'class:read',
      'class:update',
      'class:delete',
      'class:manage',
      'section:create',
      'section:read',
      'section:update',
      'section:delete',
      'section:manage',
      'academic_class:create',
      'academic_class:read',
      'academic_class:update',
      'academic_class:delete',
      'academic_class:manage',
      'subject:create',
      'subject:read',
      'subject:update',
      'subject:delete',
      'subject:manage',
      'class_subject:create',
      'class_subject:read',
      'class_subject:update',
      'class_subject:delete',
      'class_subject:manage',
      'teacher_assignment:create',
      'teacher_assignment:read',
      'teacher_assignment:update',
      'teacher_assignment:delete',
      'teacher_assignment:manage',
      'academic_enrollment:create',
      'academic_enrollment:read',
      'academic_enrollment:update',
      'academic_enrollment:delete',
      'academic_enrollment:manage',
      'class_teacher:assign',
      'timetable:read',
      'timetable:publish',
      'timetable_entry:create',
      'timetable_entry:read',
      'timetable_entry:update',
      'period:read',
      'room:read',
      'student:read',
      'attendance:create',
      'attendance:mark',
      'attendance:read',
      'attendance:update',
      'attendance:submit',
      'attendance:approve',
      'attendance:lock',
      'attendance:correct',
      'attendance:report',
      'attendance:export',
      'holiday:create',
      'holiday:read',
      'holiday:update',
      'exam:read',
      'marks:entry',
      'marks:verify',
      'report_card:generate',
      'leave:approve',
      'announcement:publish',
    ],
  },
  {
    name: 'TEACHER',
    userType: UserType.TEACHER,
    description: 'Faculty member managing classroom, daily attendance, homework, and marks',
    permissions: [
      'class:read',
      'section:read',
      'academic_class:read',
      'subject:read',
      'class_subject:read',
      'teacher_assignment:read',
      'academic_enrollment:read',
      'timetable:read',
      'timetable_entry:read',
      'period:read',
      'room:read',
      'student:read',
      'student_document:read',
      'enrollment:read',
      'attendance:create',
      'attendance:mark',
      'attendance:read',
      'attendance:submit',
      'attendance:correct',
      'attendance:report',
      'holiday:read',
      'homework:create',
      'homework:read',
      'homework:update',
      'homework:grade',
      'marks:entry',
      'leave:apply',
      'announcement:publish',
      'employee:read',
      'teacher:read',
    ],
  },
  {
    name: 'ACCOUNTANT',
    userType: UserType.ACCOUNTANT,
    description: 'Finance Officer handling billing, fee collections, and invoices',
    permissions: [
      'fee_structure:read',
      'fee_structure:update',
      'fee_invoice:create',
      'fee_invoice:read',
      'fee_invoice:void',
      'student:read',
      'payment:collect',
      'payment:read',
      'payment:refund',
      'leave:apply',
    ],
  },
  {
    name: 'HR_MANAGER',
    userType: UserType.HR_MANAGER,
    description: 'Human Resources Officer handling employee records, leave, and payroll',
    permissions: [
      'teacher:manage',
      'staff:manage',
      'employee:create',
      'employee:read',
      'employee:update',
      'employee:delete',
      'employee:activate',
      'employee:deactivate',
      'employee:suspend',
      'employee:terminate',
      'employee:restore',
      'teacher:create',
      'teacher:read',
      'teacher:update',
      'teacher:delete',
      'department:create',
      'department:read',
      'department:update',
      'department:delete',
      'designation:create',
      'designation:read',
      'designation:update',
      'designation:delete',
      'staff_attendance:mark',
      'staff_attendance:read',
      'leave:apply',
      'leave:approve',
      'payroll:calculate',
      'payroll:disburse',
    ],
  },
  {
    name: 'LIBRARIAN',
    userType: UserType.LIBRARIAN,
    description: 'Library custodian overseeing cataloging, loans, and returns',
    permissions: ['student:read', 'library:catalog', 'library:circulation', 'leave:apply'],
  },
  {
    name: 'TRANSPORT_MANAGER',
    userType: UserType.TRANSPORT_MANAGER,
    description: 'Logistics coordinator managing buses, routes, and stops',
    permissions: ['student:read', 'transport:fleet', 'transport:assign', 'leave:apply'],
  },
  {
    name: 'HOSTEL_MANAGER',
    userType: UserType.HOSTEL_MANAGER,
    description: 'Hostel warden managing buildings, rooms, and student bed allocations',
    permissions: ['student:read', 'hostel:manage', 'hostel:allocate', 'leave:apply'],
  },
  {
    name: 'RECEPTIONIST',
    userType: UserType.RECEPTIONIST,
    description: 'Front desk coordinator managing visitor inquiries and admissions',
    permissions: [
      'student:read',
      'student:create',
      'guardian:read',
      'guardian:create',
      'relationship:read',
      'relationship:create',
      'enrollment:read',
      'enrollment:create',
      'admission:create',
      'admission:read',
      'leave:apply',
    ],
  },
  {
    name: 'STAFF',
    userType: UserType.STAFF,
    description: 'General support employee with basic self-service portal access',
    permissions: ['leave:apply'],
  },
  {
    name: 'STUDENT',
    userType: UserType.STUDENT,
    description: 'Enrolled learner accessing timetables, attendance, homework, and reports',
    permissions: [
      'class:read',
      'section:read',
      'academic_class:read',
      'subject:read',
      'class_subject:read',
      'teacher_assignment:read',
      'academic_enrollment:read',
      'student:read',
      'student_document:read',
      'enrollment:read',
      'attendance:read',
      'holiday:read',
      'homework:read',
      'homework:submit',
      'fee_invoice:read',
    ],
  },
  {
    name: 'PARENT',
    userType: UserType.PARENT,
    description: 'Guardian tracking student progress, fee payments, and announcements',
    permissions: [
      'class:read',
      'section:read',
      'academic_class:read',
      'subject:read',
      'class_subject:read',
      'teacher_assignment:read',
      'academic_enrollment:read',
      'student:read',
      'student_document:read',
      'enrollment:read',
      'attendance:read',
      'holiday:read',
      'homework:read',
      'fee_invoice:read',
    ],
  },
];
