export enum UserType {
  SUPER_ADMIN = 'SUPER_ADMIN',
  SCHOOL_ADMIN = 'SCHOOL_ADMIN',
  PRINCIPAL = 'PRINCIPAL',
  VICE_PRINCIPAL = 'VICE_PRINCIPAL',
  TEACHER = 'TEACHER',
  ACCOUNTANT = 'ACCOUNTANT',
  HR_MANAGER = 'HR_MANAGER',
  LIBRARIAN = 'LIBRARIAN',
  TRANSPORT_MANAGER = 'TRANSPORT_MANAGER',
  HOSTEL_MANAGER = 'HOSTEL_MANAGER',
  RECEPTIONIST = 'RECEPTIONIST',
  STAFF = 'STAFF',
  STUDENT = 'STUDENT',
  PARENT = 'PARENT',
}

export enum UserStatus {
  PENDING_VERIFICATION = 'PENDING_VERIFICATION',
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  LOCKED = 'LOCKED',
  DEACTIVATED = 'DEACTIVATED',
}

export enum StudentStatus {
  PROSPECT = 'PROSPECT',
  APPLICANT = 'APPLICANT',
  APPLIED = 'APPLIED',
  ADMITTED = 'ADMITTED',
  ACTIVE = 'ACTIVE',
  ON_LEAVE = 'ON_LEAVE',
  PROMOTED = 'PROMOTED',
  SUSPENDED = 'SUSPENDED',
  TRANSFERRED = 'TRANSFERRED',
  GRADUATED = 'GRADUATED',
  WITHDRAWN = 'WITHDRAWN',
  EXPELLED = 'EXPELLED',
  INACTIVE = 'INACTIVE',
  ARCHIVED = 'ARCHIVED',
}

export enum AdmissionStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  INTERVIEW_SCHEDULED = 'INTERVIEW_SCHEDULED',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  ENROLLED = 'ENROLLED',
}

export enum ExamStatus {
  DRAFT = 'DRAFT',
  SCHEDULED = 'SCHEDULED',
  ONGOING = 'ONGOING',
  COMPLETED = 'COMPLETED',
  MARKS_ENTRY = 'MARKS_ENTRY',
  VERIFICATION = 'VERIFICATION',
  RESULTS_PENDING = 'RESULTS_PENDING',
  RESULTS_APPROVED = 'RESULTS_APPROVED',
  PUBLISHED = 'PUBLISHED',
  LOCKED = 'LOCKED',
  ARCHIVED = 'ARCHIVED',
}

export enum ExamType {
  UNIT_TEST = 'UNIT_TEST',
  PERIODIC_TEST = 'PERIODIC_TEST',
  MID_TERM = 'MID_TERM',
  HALF_YEARLY = 'HALF_YEARLY',
  PRE_BOARD = 'PRE_BOARD',
  FINAL = 'FINAL',
  PRACTICAL = 'PRACTICAL',
  INTERNAL_ASSESSMENT = 'INTERNAL_ASSESSMENT',
}

export enum MarkStatus {
  NOT_ENTERED = 'NOT_ENTERED',
  PRESENT = 'PRESENT',
  ABSENT = 'ABSENT',
  EXEMPT = 'EXEMPT',
  ENTERED = 'ENTERED',
  VERIFIED = 'VERIFIED',
  LOCKED = 'LOCKED',
}

export enum ResultStatus {
  PASS = 'PASS',
  FAIL = 'FAIL',
  INCOMPLETE = 'INCOMPLETE',
  WITHHELD = 'WITHHELD',
}


export enum AttendanceStatus {
  PRESENT = 'PRESENT',
  ABSENT = 'ABSENT',
  LATE = 'LATE',
  HALF_DAY = 'HALF_DAY',
  EXCUSED = 'EXCUSED',
}

export enum AttendanceMode {
  DAILY = 'DAILY',
  PERIOD = 'PERIOD',
  BOTH = 'BOTH',
}

export enum AttendanceLifecycleStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  APPROVED = 'APPROVED',
  LOCKED = 'LOCKED',
}

export enum CorrectionStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum HolidayType {
  PUBLIC_HOLIDAY = 'PUBLIC_HOLIDAY',
  SCHOOL_HOLIDAY = 'SCHOOL_HOLIDAY',
  TERM_BREAK = 'TERM_BREAK',
  EMERGENCY_CLOSURE = 'EMERGENCY_CLOSURE',
}

export enum FeeFrequency {
  ONE_TIME = 'ONE_TIME',
  MONTHLY = 'MONTHLY',
  QUARTERLY = 'QUARTERLY',
  HALF_YEARLY = 'HALF_YEARLY',
  ANNUAL = 'ANNUAL',
}

export enum FeeCategoryType {
  TUITION = 'TUITION',
  TRANSPORT = 'TRANSPORT',
  HOSTEL = 'HOSTEL',
  LAB = 'LAB',
  LIBRARY = 'LIBRARY',
  EXAMINATION = 'EXAMINATION',
  SPORTS = 'SPORTS',
  ADMISSION = 'ADMISSION',
  ACTIVITY = 'ACTIVITY',
  MISCELLANEOUS = 'MISCELLANEOUS',
}

export enum DiscountType {
  PERCENTAGE = 'PERCENTAGE',
  FLAT = 'FLAT',
}

export enum LateFeeType {
  FLAT = 'FLAT',
  DAILY_RATE = 'DAILY_RATE',
  PERCENTAGE = 'PERCENTAGE',
}

export enum InvoiceStatus {
  DRAFT = 'DRAFT',
  ISSUED = 'ISSUED',
  PARTIALLY_PAID = 'PARTIALLY_PAID',
  PAID = 'PAID',
  OVERDUE = 'OVERDUE',
  VOID = 'VOID',
  CANCELLED = 'CANCELLED',
}

export enum PaymentStatus {
  INITIATED = 'INITIATED',
  SUCCESS = 'SUCCESS',
  FAILED = 'FAILED',
  REFUNDED = 'REFUNDED',
  PARTIALLY_REFUNDED = 'PARTIALLY_REFUNDED',
}

export enum RefundStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  PROCESSED = 'PROCESSED',
}

export enum ReconciliationStatus {
  MATCHED = 'MATCHED',
  DISCREPANCY = 'DISCREPANCY',
  UNMATCHED = 'UNMATCHED',
}

export enum PaymentMethod {
  CASH = 'CASH',
  CHEQUE = 'CHEQUE',
  BANK_TRANSFER = 'BANK_TRANSFER',
  CREDIT_CARD = 'CREDIT_CARD',
  UPI = 'UPI',
  PAYMENT_GATEWAY = 'PAYMENT_GATEWAY',
}

export enum PaymentGatewayProvider {
  OFFLINE = 'OFFLINE',
  RAZORPAY = 'RAZORPAY',
  STRIPE = 'STRIPE',
  PAYPAL = 'PAYPAL',
}

export enum LeaveStatus {
  DRAFT = 'DRAFT',
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
  WITHDRAWN = 'WITHDRAWN',
}

export enum TenantPlan {
  STARTER = 'STARTER',
  GROWTH = 'GROWTH',
  ENTERPRISE = 'ENTERPRISE',
}

export enum TenantBillingStatus {
  TRIAL = 'TRIAL',
  ACTIVE = 'ACTIVE',
  PAST_DUE = 'PAST_DUE',
  SUSPENDED = 'SUSPENDED',
  CANCELLED = 'CANCELLED',
}

export enum TenantStatus {
  PENDING = 'PENDING',
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  ARCHIVED = 'ARCHIVED',
}

export enum CampusStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  ARCHIVED = 'ARCHIVED',
}

export enum AcademicYearStatus {
  DRAFT = 'DRAFT',
  ACTIVE = 'ACTIVE',
  CLOSED = 'CLOSED',
  ARCHIVED = 'ARCHIVED',
}

export enum OnboardingStatus {
  NOT_STARTED = 'NOT_STARTED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
}

export enum WeekDay {
  MONDAY = 'MONDAY',
  TUESDAY = 'TUESDAY',
  WEDNESDAY = 'WEDNESDAY',
  THURSDAY = 'THURSDAY',
  FRIDAY = 'FRIDAY',
  SATURDAY = 'SATURDAY',
  SUNDAY = 'SUNDAY',
}

export enum EmploymentStatus {
  ACTIVE = 'ACTIVE',
  PROBATION = 'PROBATION',
  ON_LEAVE = 'ON_LEAVE',
  SUSPENDED = 'SUSPENDED',
  RESIGNED = 'RESIGNED',
  TERMINATED = 'TERMINATED',
  RETIRED = 'RETIRED',
  INACTIVE = 'INACTIVE',
}

export enum EmploymentType {
  FULL_TIME = 'FULL_TIME',
  PART_TIME = 'PART_TIME',
  CONTRACT = 'CONTRACT',
  INTERN = 'INTERN',
  AD_HOC = 'AD_HOC',
}

export enum Gender {
  MALE = 'MALE',
  FEMALE = 'FEMALE',
  OTHER = 'OTHER',
}

export enum StaffDocumentType {
  ID_PROOF = 'ID_PROOF',
  RESUME = 'RESUME',
  QUALIFICATION_CERTIFICATE = 'QUALIFICATION_CERTIFICATE',
  EXPERIENCE_LETTER = 'EXPERIENCE_LETTER',
  JOINING_LETTER = 'JOINING_LETTER',
  POLICE_VERIFICATION = 'POLICE_VERIFICATION',
  OTHER = 'OTHER',
}

export enum GuardianRelationType {
  FATHER = 'FATHER',
  MOTHER = 'MOTHER',
  GUARDIAN = 'GUARDIAN',
  GRANDPARENT = 'GRANDPARENT',
  OTHER = 'OTHER',
}

export enum StudentDocumentType {
  BIRTH_CERTIFICATE = 'BIRTH_CERTIFICATE',
  TRANSFER_CERTIFICATE = 'TRANSFER_CERTIFICATE',
  PREVIOUS_MARKSHEET = 'PREVIOUS_MARKSHEET',
  ID_PROOF = 'ID_PROOF',
  MEDICAL_RECORD = 'MEDICAL_RECORD',
  IMMUNIZATION_RECORD = 'IMMUNIZATION_RECORD',
  ADDRESS_PROOF = 'ADDRESS_PROOF',
  OTHER = 'OTHER',
}

export enum DocumentVerificationStatus {
  UPLOADED = 'UPLOADED',
  PENDING_VERIFICATION = 'PENDING_VERIFICATION',
  VERIFIED = 'VERIFIED',
  REJECTED = 'REJECTED',
  ARCHIVED = 'ARCHIVED',
}

export enum AdmissionType {
  REGULAR = 'REGULAR',
  TRANSFER = 'TRANSFER',
  SCHOLARSHIP = 'SCHOLARSHIP',
  MANAGEMENT = 'MANAGEMENT',
}

export enum EducationLevel {
  PRE_PRIMARY = 'PRE_PRIMARY',
  PRIMARY = 'PRIMARY',
  MIDDLE = 'MIDDLE',
  SECONDARY = 'SECONDARY',
  SENIOR_SECONDARY = 'SENIOR_SECONDARY',
  HIGHER_EDUCATION = 'HIGHER_EDUCATION',
}

export enum AcademicStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  ARCHIVED = 'ARCHIVED',
}

export enum SubjectCategory {
  CORE = 'CORE',
  ELECTIVE = 'ELECTIVE',
  OPTIONAL = 'OPTIONAL',
  PRACTICAL = 'PRACTICAL',
  CO_CURRICULAR = 'CO_CURRICULAR',
}

export enum TeacherAssignmentStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  COMPLETED = 'COMPLETED',
  TRANSFERRED = 'TRANSFERRED',
}

export enum PeriodType {
  TEACHING = 'TEACHING',
  BREAK = 'BREAK',
  LUNCH = 'LUNCH',
  ACTIVITY = 'ACTIVITY',
  ASSEMBLY = 'ASSEMBLY',
}

export enum TimetableStatus {
  DRAFT = 'DRAFT',
  PUBLISHED = 'PUBLISHED',
  ARCHIVED = 'ARCHIVED',
}

export enum RoomType {
  CLASSROOM = 'CLASSROOM',
  LABORATORY = 'LABORATORY',
  COMPUTER_LAB = 'COMPUTER_LAB',
  AUDITORIUM = 'AUDITORIUM',
  LIBRARY = 'LIBRARY',
  WORKSHOP = 'WORKSHOP',
  OTHER = 'OTHER',
}

export enum TimetableEntryStatus {
  ACTIVE = 'ACTIVE',
  CANCELLED = 'CANCELLED',
}

export enum AssignmentType {
  HOMEWORK = 'HOMEWORK',
  ASSIGNMENT = 'ASSIGNMENT',
  PROJECT = 'PROJECT',
  PRACTICE = 'PRACTICE',
  CLASSWORK = 'CLASSWORK',
  OTHER = 'OTHER',
}

export enum AssignmentStatus {
  DRAFT = 'DRAFT',
  PUBLISHED = 'PUBLISHED',
  CLOSED = 'CLOSED',
  ARCHIVED = 'ARCHIVED',
}

export enum SubmissionType {
  ONLINE_FILE = 'ONLINE_FILE',
  ONLINE_TEXT = 'ONLINE_TEXT',
  BOTH = 'BOTH',
  OFFLINE = 'OFFLINE',
}

export enum AssignmentTargetType {
  ALL = 'ALL',
  SPECIFIC_STUDENTS = 'SPECIFIC_STUDENTS',
}

export enum AssignmentSubmissionStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  LATE = 'LATE',
  GRADED = 'GRADED',
  RETURNED = 'RETURNED',
}

export enum StudentAssignmentStatus {
  NOT_STARTED = 'NOT_STARTED',
  IN_PROGRESS = 'IN_PROGRESS',
  SUBMITTED = 'SUBMITTED',
  LATE = 'LATE',
  GRADED = 'GRADED',
  OVERDUE = 'OVERDUE',
}

export enum LeaveDurationType {
  FULL_DAY = 'FULL_DAY',
  HALF_DAY = 'HALF_DAY',
}

export enum HalfDayPeriod {
  FIRST_HALF = 'FIRST_HALF',
  SECOND_HALF = 'SECOND_HALF',
}

export enum LeaveAccrualMode {
  ANNUAL = 'ANNUAL',
  MONTHLY = 'MONTHLY',
  QUARTERLY = 'QUARTERLY',
}

export enum SalaryComponentType {
  EARNING = 'EARNING',
  DEDUCTION = 'DEDUCTION',
}

export enum ComponentCalculationType {
  FIXED = 'FIXED',
  PERCENTAGE = 'PERCENTAGE',
}

export enum PayrollPeriodStatus {
  DRAFT = 'DRAFT',
  OPEN = 'OPEN',
  PROCESSING = 'PROCESSING',
  CALCULATED = 'CALCULATED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  APPROVED = 'APPROVED',
  PROCESSED = 'PROCESSED',
  LOCKED = 'LOCKED',
  CANCELLED = 'CANCELLED',
}

export enum PayrollPaymentStatus {
  UNPAID = 'UNPAID',
  PAYMENT_PENDING = 'PAYMENT_PENDING',
  PAID = 'PAID',
  FAILED = 'FAILED',
  REVERSED = 'REVERSED',
}

export enum PayrollAdjustmentType {
  BONUS = 'BONUS',
  INCENTIVE = 'INCENTIVE',
  ARREARS = 'ARREARS',
  REIMBURSEMENT = 'REIMBURSEMENT',
  ONE_TIME_DEDUCTION = 'ONE_TIME_DEDUCTION',
  ADVANCE_DEDUCTION = 'ADVANCE_DEDUCTION',
}

export enum OvertimeStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  PROCESSED = 'PROCESSED',
}

export enum StatutoryType {
  PF = 'PF',
  ESI = 'ESI',
  PROFESSIONAL_TAX = 'PROFESSIONAL_TAX',
  TDS = 'TDS',
  OTHER = 'OTHER',
}

export enum HRDocumentType {
  ID_PROOF = 'ID_PROOF',
  ADDRESS_PROOF = 'ADDRESS_PROOF',
  EDUCATION_CERTIFICATE = 'EDUCATION_CERTIFICATE',
  EXPERIENCE_CERTIFICATE = 'EXPERIENCE_CERTIFICATE',
  OFFER_LETTER = 'OFFER_LETTER',
  APPOINTMENT_LETTER = 'APPOINTMENT_LETTER',
  CONTRACT = 'CONTRACT',
  RESIGNATION_LETTER = 'RESIGNATION_LETTER',
  OTHER = 'OTHER',
}

// ============================================================================
// Phase 15: Library Management Enums
// ============================================================================

export enum BookCopyStatus {
  AVAILABLE = 'AVAILABLE',
  ISSUED = 'ISSUED',
  RESERVED = 'RESERVED',
  OVERDUE = 'OVERDUE',
  LOST = 'LOST',
  DAMAGED = 'DAMAGED',
  UNDER_REPAIR = 'UNDER_REPAIR',
  WITHDRAWN = 'WITHDRAWN',
  ARCHIVED = 'ARCHIVED',
}

export enum BookCondition {
  NEW = 'NEW',
  GOOD = 'GOOD',
  FAIR = 'FAIR',
  DAMAGED = 'DAMAGED',
  LOST = 'LOST',
}

export enum LibraryMemberType {
  STUDENT = 'STUDENT',
  TEACHER = 'TEACHER',
  STAFF = 'STAFF',
}

export enum LibraryMemberStatus {
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  EXPIRED = 'EXPIRED',
  CLOSED = 'CLOSED',
}

export enum CirculationStatus {
  ISSUED = 'ISSUED',
  RETURNED = 'RETURNED',
  OVERDUE = 'OVERDUE',
  LOST = 'LOST',
  DAMAGED = 'DAMAGED',
  CANCELLED = 'CANCELLED',
}

export enum ReservationStatus {
  PENDING = 'PENDING',
  READY = 'READY',
  FULFILLED = 'FULFILLED',
  CANCELLED = 'CANCELLED',
  EXPIRED = 'EXPIRED',
}

export enum LibraryFineType {
  OVERDUE = 'OVERDUE',
  LOST_BOOK = 'LOST_BOOK',
  DAMAGED_BOOK = 'DAMAGED_BOOK',
  MANUAL_PENALTY = 'MANUAL_PENALTY',
}

export enum LibraryFineStatus {
  PENDING = 'PENDING',
  PARTIALLY_PAID = 'PARTIALLY_PAID',
  PAID = 'PAID',
  WAIVED = 'WAIVED',
  CANCELLED = 'CANCELLED',
}

export enum FineCalculationMethod {
  DAILY_RATE = 'DAILY_RATE',
  FIXED = 'FIXED',
  PERCENTAGE = 'PERCENTAGE',
}

export enum BookWithdrawalReason {
  LOST = 'LOST',
  DAMAGED_BEYOND_REPAIR = 'DAMAGED_BEYOND_REPAIR',
  OBSOLETE = 'OBSOLETE',
  DUPLICATE = 'DUPLICATE',
  OTHER = 'OTHER',
}

export enum DamagedBookAction {
  REPAIR = 'REPAIR',
  REPLACE = 'REPLACE',
  CONTINUE_CIRCULATION = 'CONTINUE_CIRCULATION',
  WITHDRAW = 'WITHDRAW',
}

