export enum UserType {
  SUPER_ADMIN = 'SUPER_ADMIN',
  SCHOOL_ADMIN = 'SCHOOL_ADMIN',
  PRINCIPAL = 'PRINCIPAL',
  VICE_PRINCIPAL = 'VICE_PRINCIPAL',
  TEACHER = 'TEACHER',
  ACCOUNTANT = 'ACCOUNTANT',
  HR_MANAGER = 'HR_MANAGER',
  LIBRARIAN = 'LIBRARIAN',
  TRANSPORT_MANAGER = 'TRANSPORT_MANAGER',
  HOSTEL_MANAGER = 'HOSTEL_MANAGER',
  RECEPTIONIST = 'RECEPTIONIST',
  STAFF = 'STAFF',
  STUDENT = 'STUDENT',
  PARENT = 'PARENT',
}

export enum UserStatus {
  PENDING_VERIFICATION = 'PENDING_VERIFICATION',
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  LOCKED = 'LOCKED',
  DEACTIVATED = 'DEACTIVATED',
}

export enum StudentStatus {
  PROSPECT = 'PROSPECT',
  APPLICANT = 'APPLICANT',
  APPLIED = 'APPLIED',
  ADMITTED = 'ADMITTED',
  ACTIVE = 'ACTIVE',
  ON_LEAVE = 'ON_LEAVE',
  PROMOTED = 'PROMOTED',
  SUSPENDED = 'SUSPENDED',
  TRANSFERRED = 'TRANSFERRED',
  GRADUATED = 'GRADUATED',
  WITHDRAWN = 'WITHDRAWN',
  EXPELLED = 'EXPELLED',
  INACTIVE = 'INACTIVE',
  ARCHIVED = 'ARCHIVED',
}

export enum AdmissionStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  INTERVIEW_SCHEDULED = 'INTERVIEW_SCHEDULED',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  ENROLLED = 'ENROLLED',
}

export enum ExamStatus {
  DRAFT = 'DRAFT',
  SCHEDULED = 'SCHEDULED',
  MARKS_ENTRY = 'MARKS_ENTRY',
  VERIFICATION = 'VERIFICATION',
  PUBLISHED = 'PUBLISHED',
  LOCKED = 'LOCKED',
}

export enum AttendanceStatus {
  PRESENT = 'PRESENT',
  ABSENT = 'ABSENT',
  LATE = 'LATE',
  HALF_DAY = 'HALF_DAY',
  EXCUSED = 'EXCUSED',
}

export enum InvoiceStatus {
  DRAFT = 'DRAFT',
  ISSUED = 'ISSUED',
  PARTIALLY_PAID = 'PARTIALLY_PAID',
  PAID = 'PAID',
  OVERDUE = 'OVERDUE',
  VOID = 'VOID',
}

export enum PaymentStatus {
  INITIATED = 'INITIATED',
  SUCCESS = 'SUCCESS',
  FAILED = 'FAILED',
  REFUNDED = 'REFUNDED',
}

export enum PaymentMethod {
  CASH = 'CASH',
  CHEQUE = 'CHEQUE',
  BANK_TRANSFER = 'BANK_TRANSFER',
  CREDIT_CARD = 'CREDIT_CARD',
  UPI = 'UPI',
  PAYMENT_GATEWAY = 'PAYMENT_GATEWAY',
}

export enum PaymentGatewayProvider {
  OFFLINE = 'OFFLINE',
  RAZORPAY = 'RAZORPAY',
  STRIPE = 'STRIPE',
  PAYPAL = 'PAYPAL',
}

export enum LeaveStatus {
  DRAFT = 'DRAFT',
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
}

export enum TenantPlan {
  STARTER = 'STARTER',
  GROWTH = 'GROWTH',
  ENTERPRISE = 'ENTERPRISE',
}

export enum TenantBillingStatus {
  TRIAL = 'TRIAL',
  ACTIVE = 'ACTIVE',
  PAST_DUE = 'PAST_DUE',
  SUSPENDED = 'SUSPENDED',
  CANCELLED = 'CANCELLED',
}

export enum TenantStatus {
  PENDING = 'PENDING',
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  ARCHIVED = 'ARCHIVED',
}

export enum CampusStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  ARCHIVED = 'ARCHIVED',
}

export enum AcademicYearStatus {
  DRAFT = 'DRAFT',
  ACTIVE = 'ACTIVE',
  CLOSED = 'CLOSED',
  ARCHIVED = 'ARCHIVED',
}

export enum OnboardingStatus {
  NOT_STARTED = 'NOT_STARTED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
}

export enum WeekDay {
  MONDAY = 'MONDAY',
  TUESDAY = 'TUESDAY',
  WEDNESDAY = 'WEDNESDAY',
  THURSDAY = 'THURSDAY',
  FRIDAY = 'FRIDAY',
  SATURDAY = 'SATURDAY',
  SUNDAY = 'SUNDAY',
}

export enum EmploymentStatus {
  ACTIVE = 'ACTIVE',
  PROBATION = 'PROBATION',
  ON_LEAVE = 'ON_LEAVE',
  SUSPENDED = 'SUSPENDED',
  RESIGNED = 'RESIGNED',
  TERMINATED = 'TERMINATED',
  RETIRED = 'RETIRED',
  INACTIVE = 'INACTIVE',
}

export enum EmploymentType {
  FULL_TIME = 'FULL_TIME',
  PART_TIME = 'PART_TIME',
  CONTRACT = 'CONTRACT',
  INTERN = 'INTERN',
  AD_HOC = 'AD_HOC',
}

export enum Gender {
  MALE = 'MALE',
  FEMALE = 'FEMALE',
  OTHER = 'OTHER',
}

export enum StaffDocumentType {
  ID_PROOF = 'ID_PROOF',
  RESUME = 'RESUME',
  QUALIFICATION_CERTIFICATE = 'QUALIFICATION_CERTIFICATE',
  EXPERIENCE_LETTER = 'EXPERIENCE_LETTER',
  JOINING_LETTER = 'JOINING_LETTER',
  POLICE_VERIFICATION = 'POLICE_VERIFICATION',
  OTHER = 'OTHER',
}

export enum GuardianRelationType {
  FATHER = 'FATHER',
  MOTHER = 'MOTHER',
  GUARDIAN = 'GUARDIAN',
  GRANDPARENT = 'GRANDPARENT',
  OTHER = 'OTHER',
}

export enum StudentDocumentType {
  BIRTH_CERTIFICATE = 'BIRTH_CERTIFICATE',
  TRANSFER_CERTIFICATE = 'TRANSFER_CERTIFICATE',
  PREVIOUS_MARKSHEET = 'PREVIOUS_MARKSHEET',
  ID_PROOF = 'ID_PROOF',
  MEDICAL_RECORD = 'MEDICAL_RECORD',
  IMMUNIZATION_RECORD = 'IMMUNIZATION_RECORD',
  ADDRESS_PROOF = 'ADDRESS_PROOF',
  OTHER = 'OTHER',
}

export enum DocumentVerificationStatus {
  UPLOADED = 'UPLOADED',
  PENDING_VERIFICATION = 'PENDING_VERIFICATION',
  VERIFIED = 'VERIFIED',
  REJECTED = 'REJECTED',
  ARCHIVED = 'ARCHIVED',
}

export enum AdmissionType {
  REGULAR = 'REGULAR',
  TRANSFER = 'TRANSFER',
  SCHOLARSHIP = 'SCHOLARSHIP',
  MANAGEMENT = 'MANAGEMENT',
}
